open-power/op-test

common/OpTestBMC.py, common/OpTestConnection.py, common/OpTestConstants.py, common/OpTestError.py, common/OpTestIPMI.py, common/OpTestSystem.py
I have made same changes in the basic framework of OpTest like adding exception and constants.
Let me know what you think about this
=> Incorporating open power common test framework

common/OpTestIPMI.py, common/OpTestSystem.py
=> Added the new functionality for chassis power cycle ipmi command

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, testcases/OpTestHeartbeat.py
=> Adding the HeartBeat KOPAL Daemon test case

bvt/op-firmware-component-update-bvt.xml, bvt/op-firmware-component-update.xml, ci/source/op_firmware_component_update.py, ci/source/test_op_firmware_component_update.py
=> Firmware update tests for individual PNOR and BMC components

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, common/OpTestConstants.py, common/OpTestUtil.py, testcases/OpTestMtdPnorDriver.py
=> Test case for mtd pnor driver

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, testcases/OpTestInbandIPMI.py
=> Inband IPMI Functionality test cases

bvt/op-ci-bmc-run
=> Importing the op_firmware_component_update class line

ci/source/op_ci_bmc.py, common/OpTestBMC.py, common/OpTestConstants.py, common/OpTestIPMI.py, common/OpTestLpar.py, common/OpTestSystem.py, common/OpTestUtil.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/32)
=> Update github branch with auto-test latest changes

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/29)
=> Required perl modules to use the framework

common/OpTestLpar.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/38)
=> Fix the import pxssh error issue.

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, common/OpTestConstants.py, testcases/OpTestHMIHandling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/39)
=> Add the timer facility and chip TOD error injections.

common/util/__init__.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/43)
=> Adding the missing __init__.py file in common/util/ directory

bvt/op-bmc-web-update-bvt.xml, bvt/op-bmc-web-update.xml, bvt/op-ci-bmc-run, ci/source/op_bmc_web_update.py, ci/source/test_op_bmc_web_update.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/42)
=> Test case wrapper scripts for BMC WEB GUI Firmware components update

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, common/OpTestConstants.py, common/OpTestIPMI.py, common/OpTestSystem.py, testcases/OpTestIPMIPowerControl.py
This test case tests system power control operations like power ON/OFF/Cycle/Soft/Reset.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/47)
=> Test case for system power control.

bvt/op-opal-ci.xml, ci/source/op_ci_bmc.py, common/OpTestBMC.py
By using this patch, we will get BMC and PNOR Version side info(Golden or Primary) before and after
PNOR FW Flash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/48)
=> Adding the get_side_acivated function in pnor image flash procedure.

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, common/OpTestConstants.py, testcases/OpTestInbandUsbInterface.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/58)
=> Add inband ipmi tests for USB[BT] interface.

bvt/op-ci-bmc-run, bvt/op-occ-fvt-bvt.xml
This PR fixes missing occ fvt master bvt xml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/65)
=> Occ fvt fix

bvt/op-fwts-fvt.xml, ci/source/op_fwts_fvt.py, ci/source/op_opal_fvt.py, ci/source/test_fwts_fvt.py, common/OpTestConstants.py, common/OpTestHost.py, testcases/OpTestFWTS.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/73)
=> Remove dependencies and make FWTS execution more cleaner. 

bvt/op-conformance1-bvt.xml, bvt/op-conformance2-bvt.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/72)
=> Master Conformance bvt xml files

README.md, bvt/op-inbound-basic.xml, bvt/op-occ-fvt.xml, bvt/op-opal-fvt-bvt.xml, bvt/op-opal-fvt.xml, bvt/op-outofband-firmware-update.xml, ci/source/op_occ_fvt.py, ci/source/test_occ_fvt.py, common/OpTestConstants.py, run, testcases/OpTestEM.py, testcases/OpTestEnergyScale.py, testcases/OpTestOCC.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/71)
=> Add missing constants.

bvt/run-op-bvt, bvt/run-op-it, run
e.g.
./run --machine fstn5 --noflash --test="Test Init"
Will just run the "Test Init" test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/79)
=> Support running just one test

bvt/op-machines-example.xml, bvt/op-machines.xsd, bvt/op-opal-fvt.xml, ci/source/op_ci_bmc.py, ci/source/op_opal_fvt.py, ci/source/test_opal_fvt.py, common/OpTestBMC.py, common/OpTestConstants.py, common/OpTestHost.py, common/OpTestSystem.py, run, testcases/OpTestPCI.py
This testcase is a start for adding pci or IO subsystem related testcases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/76)
=> Add test case for pci subsystem info.

bvt/op-opal-fvt.xml, ci/source/op_opal_fvt.py, common/OpTestConstants.py, common/OpTestIPMI.py, testcases/OpTestFastReboot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/81)
=> Fast reset test case

bvt/op-fwts-fvt.xml, bvt/op-occ-fvt.xml, bvt/op-opal-fvt.xml, ci/source/op_fwts_fvt.py, ci/source/op_occ_fvt.py, ci/source/op_opal_fvt.py, testcases/OpTestEM.py, testcases/OpTestFWTS.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/83)
=> Convert all tests to Unittest based execution.

bvt/op-fwts-fvt.xml, ci/source/op_fwts_fvt.py, ci/source/op_opal_fvt.py, common/OpTestConstants.py, testcases/OpTestFWTS.py, testcases/OpTestInbandIPMI.py, testcases/fwts_execution.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/84)
=> Enhancements

common/OpTestHost.py, testcases/OpTestI2Cdriver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/87)
=> I2c improvements

bvt/op-opal-fsp-fvt.xml, ci/source/op_opal_fvt.py, common/OpTestASM.py, common/OpTestFSP.py, common/OpTestHost.py, common/OpTestTConnection.py, testcases/OpTestDumps.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/99)
=> FSP Library 

common/OpTestHost.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/100)
=> Improve timeouts

op-test, testcases/OpalMsglog.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/106)
=> Add OPAL msglog test. Check for skiboot errors/warnings

testcases/OpTestFastReboot.py
Munge the fast reboot tests to support:
a) doing many fast reboots
b) doing fast reboot test all the way to the OS.
and add some helpers to run some fast reboot torture, which has
been useful in development
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/117)
=> OpTestFastReboot: Add some torture tests, useful in development

common/OpTestFSP.py, op-test, testcases/DPO.py, testcases/EPOW.py, testcases/OpTestDumps.py
DPO   ---> Delayed Power OFF
EPOW---> Emergency Power OFF Warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/115)
=> DPO and EPOW Testcases.

common/OpTestIPMI.py, op-test, testcases/OpTestHMIHandling.py, testcases/OpTestOCC.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/122)
=> FSP OCC reset testcase and few fixes.

testcases/BootTorture.py, testcases/OpTestPCI.py
Not sure what we should do for such torture tests.... maybe have a test suite that aims to run for a day/week that does these kind of things?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/119)
=> BootTorture: boot 1024 times to petitboot

common/OpTestIPMI.py, testcases/IpmiTorture.py, testcases/OpalErrorLog.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/139)
=> [RFC] IPMI and Console Torture tests

common/OpTestHost.py, testcases/OpTestPrdDaemon.py
Enable opal-prd on P9 FSP system and add few validations.
-Vasant
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/163)
=> Prd daemon fixes

common/Exceptions.py, common/OPexpect.py, common/OpTestConstants.py, common/OpTestHost.py, common/OpTestIPMI.py, common/OpTestOpenBMC.py, testcases/OpTestFlash.py, testcases/OpTestKernel.py, testcases/OpTestMtdPnorDriver.py
=> OpTestFlash: Force BIOS Golden side sensor to primary side

OpTestConfiguration.py, common/OpTestHost.py, testcases/InstallHostOS.py, testcases/InstallRhel.py, testcases/InstallUbuntu.py
=> Properly use full path to op-test directory

op-test
Fixes: https://github.com/open-power/op-test-framework/issues/255
=> Fix users environment version of python2 in op-test script.

common/OpTestHost.py
=> Correct the error message in host_list_gard_records()

common/OpTestHost.py, common/OpTestUtil.py
=> Util: Add copyFilesFromDest to copy files from system to local

testcases/OpTestPCI.py
Adding a "blacklist" which holds a list of device names which will not
be tested for link problems.
Signed-off-by: Brenda Lee <lbrenda@au1.ibm.com>
=> PCI link problem detection - blacklisting devices

common/OpTestUtil.py
=> Fix failure of commands due to incorrect parse of echo_rc value

testcases/OpTestEM.py
Changed the workload and changed the way the assertion works so that it's less rigid.
- idle_state_names has been updated so that only one command is run to
collect all the idle state names
- dd is not required for the workload and is therefore only run once at
the start to create a temptext.txt file which is later removed
- workload runs sha1sum rather than find as it is more CPU intensive and
runs faster
- workload runs on all CPUs as background processes
=>  Initial cpu idle states host efficiency enhancement 

testcases/OpTestHMIHandling.py
Enable the tests to cleanup the machine to run the next tests and
attempt to leave the machine state working.
=> OpTestHMIHandling: Recover machine from failures

README.md
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
=> README: Add link to documentation

common/Exceptions.py
=> Exceptions: Fix format style

OpTestConfiguration.py, common/Exceptions.py, common/OpTestHost.py, common/OpTestIPMI.py, common/OpTestUtil.py
Improve information in exceptions and formatting style.
=> OpTestUtil: Exception improvements

OpTestLogger.py, common/OpTestHost.py, common/OpTestSSH.py, common/OpTestThread.py, test_binaries/tlbie_test.c, testcases/EMStress.py, testcases/OpTestEM.py
=> Add EM Stress test using multithreading

common/OpTestIPMI.py, common/OpTestOpenBMC.py, common/OpTestSystem.py
Make eSEL and related information available on crashes
and unexpected cases.
=> OpTestSystem: Improve data available on crash

README.md
Add additional python modules needed based on options chosen.
=> README: Add python modules

testcases/OpTestCAPI.py
=> OpTestCAPI.py: stress memcpy afu with many processes

OpTestConfiguration.py, testcases/RunHostTest.py
Add support for copying results from commands ran inside
host.
=> testcases.RunHostTest: Add support for copying results from host

common/OpTestSystem.py, common/OpTestUtil.py, testcases/Console.py, testcases/KernelLog.py
=> KernelLog: Filter out urandom_read

testcases/PciSlotLocCodes.py
For QEMU/Mambo skip running the slot/label tests.
=> PciSlotLocCodes: Skip for QEMU/Mambo

common/OpTestUtil.py
Some AES SQL syntax issues can come back as ok=200 http response so
we need to special case those.
=> OpTestUtil: AES SQL error handling

testcases/KernelLog.py
Add new message to filter out, remove duplicate and
generalize another a little.
=> KernelLog: Add new filter

testcases/PciSlotLocCodes.py
Check the DT compatible field for NPU nodes to skip looking
for the slot labels.
=> PciSlotLocCodes: Skip NPU for slot label checks

op-test
Create softlink named `latest` to latest test result which
will be helpful for reference.
=> op-test: Create latest softlink to latest test result

testcases/OpTestPNOR.py
=> OpTestPNOR: Check for correct failure with Read Only PNOR TOC

testcases/InstallUpstreamKernel.py
During error cases in runTest console thread
isn't terminating and causes test not to exit and
hang forever, lets handle console termination
as part of runTest itself instead in teardown.
=> Fixup: handle console thread termination

common/OpTestMambo.py
=> Mambo: export current environ to capture LIB_DIR

testcases/OpTestPrdDaemon.py
Add some recovery logic if the opal-prd.service is having trouble
staying alive.
=> OpTestPrdDaemon: Add some recovery logic

common/OpTestHost.py, testcases/OpTestCAPI.py, testcases/OpTestOpenCAPI.py
=> Fix error reporting of capi/opencapi test cases

testcases/IplParams.py
=> IplParams: enable for dd2.3

testcases/OpTestHMIHandling.py
opal-gard commands can request interactive Y/N, so enable
the test to reply to expected conditions.
Add dd2.3 support.
=> OpTestHMIHandling: opal-gard interactive support

common/OpTestSystem.py, testcases/OpTestFastReboot.py, testcases/OpalMsglog.py
=> Qemu can do MTD device (when given pnor, which you should do)

testcases/DeviceTreeValidation.py
Not all the distros consistently output lsprop (-R) so make it consistent,
otherwise we get mismatches which get flagged as failures.
Add debug info to help assist when determining the failures.
=> DeviceTreeValidation: Add lsprop -R and debug info

HDCT.txt, OpTestConfiguration.py, common/OpTestCronus.py, common/OpTestSystem.py, common/OpTestUtil.py, op-test, testcases/testCronus.py
=> OpTestCronus: Add Cronus support

testcases/DeviceTreeValidation.py
This test validates `version` property. May be in future we can add validation for component level version property.
=> DeviceTreeValidation: Add test case to validate ibm,firmware-versions node

README.md
Update the steps to clone the skiboot source and build steps.
=> README: Clarify skiboot cloning steps

OpTestConfiguration.py
Log the git repo level to aide in triage of how dated
the repo is.
=> OpTestConfiguration: Log git level

common/OpTestOpenBMC.py
We now need to do an extra bit of hoop-jumping as our previous logic
of "REST API = vpnor" is no longer valid.
=> OpenBMC: non-vpnor systems now have REST API, change how we detect vpnor

op-test
Updating with new classname to invoke crash suite
Signed-off-by: Srikanth Aithal <sraithal@linux.vnet.ibm.com>
=> Update the caller for crash suite

common/OpTestUtil.py
The parsing of op-test configuration from hostlocker comments is prone
to breaking since we just scan for a config key + ":" in the line. I've noticed
that op-test will treat a line that ends with "Run:" as an op-test
configuration directive which caused the test to fail since the rest
of the line didn't define a valid test case.
This is kind of stupid, so make the parsing more robust by:
a) Making op-test scan for an "[op-test]" marker that indicates when the
op-test config definitions begin.
b) Only treating a line as an op-test config option if it begins with
"key:" rather than allowing it to be present anywhere in the line.
This has the side effect of allowing you to comment out a directive.
Additionally, this makes the configuration logged into the debug log,
with the exception of …
=> util: Make hostlocker config parsing more robust

README.md
It works now. 
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>
=> Readme was having wrong link, fixed the same to the new link.

common/OpTestHMC.py
added a logic as in automated installation environment
we can not get last login string so taking console
always fail, so logic loop it 2 times to login/logout to get the
last login string
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>
=> Fix issue in common:OpTestHMC

testcases/OpTestFlash.py
The previous code would iterate over every file in the tarball until it
found "version=", and then go back over the file it's in, and parse it
out from there.  Instead of doing that and potentially going through the
entire PNOR blob, directly check the MANIFEST.
This should also fix any issues with Python 3 string encoding.
Would appreciate it if people test this!
=> OpTestFlash: Rework get_version_tar() to suck less

testcases/gcov.py
Fixes up some breakage we got with the python3 switch combined with bitrot.
=> gcov: simplify and use pure sockets

op-test
Lets add MPIPL test case to hostboot suite.
=> Add MPIPL tests to hostboot test suite

common/OpTestHost.py
=> OpTestHost: python3 fix

common/OpTestUtil.py
=> Don't bail if ibm,skiboot nvram partition doesn't exist

testcases/OpTestCAPI.py
=> OpTestCAPI: add new memcpy afu test KernelAPITest

common/OpTestSystem.py
Looks like commit 093f15ecd9642e56c54ae3893074423c726bb16e accidently removed
the logic to fallback to alternate method to determine server ip when
tests run in an boxes(SUT) with older nc utility,
refer commit 403d141391f5934f548bb1d40049cfd37a020527,
this fix address it by reverting the logic back to work properly.
=> Fixup: Alternate method to get server ip for boxes with older nc utility

common/OpTestHost.py, testcases/PowerNVDump.py
Reworked MPIPL based on new Device Tree format.
Now we can seamlessly integrate this with hostboot and OPAL CI.
-Vasant
=> [MPIPL] Rework

common/OpTestFSP.py
clean up some open coding and change the format of the `smgr mfgState` and boot progress codes that get printed while waiting on a state change
=> Fsp tweaks

OpTestConfiguration.py, common/OpTestConstants.py, testcases/OpTestEnergyScale.py
Signed-off-by: Alvin Wang <alvinwang@msn.com>
=> OpTestEnergyScale: Add support for mihawk

testcases/OpTestCAPI.py
=> OpTestCAPI: add new memcpy afu CxlResetTest

testcases/OpTestDlpar.py
This scripts tests DLPAR CPU Add, Remove & Move operation
Signed-off-by: Shruthi <shruvenk@in.ibm.com>
=> DLPAR Basic Operations on LPAR

testcases/OpTestDlpar.py
This script tests extended tests with DLPAR Add, Remove, Move such as
Workload, SMT and loop.
Signed-off-by: Shruthi <shruvenk@in.ibm.com>
=> DLPAR Extended Operations of CPU

common/OpTestHost.py, testcases/DeviceTreeValidation.py, testcases/EPOW.py, testcases/IplParams.py, testcases/OpTestEM.py, testcases/OpTestFastReboot.py, testcases/OpTestHMIHandling.py, testcases/OpTestPrdDriver.py, testcases/OpalSysfsTests.py, testcases/OpalUtils.py, testcases/SbePassThrough.py, testcases/SecureBoot.py, testcases/TrustedBoot.py
Get us going on Swift system.
Signed-off-by: Mahesh Salgaonkar <mahesh@linux.vnet.ibm.com>
=> Add support for Axone processor POWER9P.

common/OpTestOpenBMC.py
While investigating an issue where op-test would fail to flash a OpenBMC
system with a new PNOR, it became clear that recent OpenBMC systems can
have 'empty' inventory lists for host firmware, which was the condition
being used so far to make a determination if the system was capable of
VPNOR or not.
Further investigation with the OpenBMC team revealed that most of the
OpenBMC builds today support VPNOR, and the only reliable way to check
is the presence of 'pflash' bundled as part of BMC root filesystem.
If 'pflash' is present, means that OpenBMC doesn't support VPNOR.
Otherwise, it should.
Fixes said scenarios described above where op-test would fail to flash
OpenBMC systems with an empty inventory list of host images.
=> OpTestOpenBMC: make query_vpnor check for pflash

.travis.yml, ci/build-qemu-powernv.sh, common/OpTestQemu.py, testcases/KernelLog.py, testcases/OpalMsglog.py, testcases/OpalSysfsTests.py
I've been trying to get the travis CI for op-test up and running again, made some changes so that it can use a Power9 pnor with a qemu target, added some exceptions that I think are safe, but I'm still hitting one nvram failure, where apparently nvram is not zeroed correctly (or at all) on Qemu.
=> Update travis focal

.travis.yml, requirements.txt
Patch addes ninja python module to travis qemu compilation issue.
=> Fix travis missing package.

op-test, testcases/OpTestLPM.py
We will be adding more tests as part of OpTestLPM tests in future and having
a test suite is a better idea for users to run all test in batch in future
=> Add code to make LPM test a LPM-suite

common/OpTestHMC.py, testcases/OpTestLPM.py
Add vNIC support for LPM Test
Author: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>
Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>
=> Add vNIC support for LPM Test

common/OpTestHMC.py, common/OpTestUtil.py, common/OpTestVIOS.py, testcases/OpTestLPM.py
Added functionality for parsing dmesg log for errors at different stages within test.
Added functionality for collecting OS logs at different stages within test. 
Collecting OS, VIOS, HMC logs when test fails.
Added provision for performing cross HMC LPM with vNIC options.
=> Dmesg Error Parsing, Log Collection, Cross HMC LPM with vNIC

testcases/OpTestDlparIO.py
The existing test does not display the console logs on stdout
and user is unware of whats happening at os kernel events, so
a monitor code is added to populate console logs at stdout
=> Capture os logs while DLPAR tests are running

common/OpTestHMC.py, doc/programming.rst
Add HMC package to the doc
common/OpTestHMC.py: add doc string data to functions
doc/programming.rst: add HMC package information
Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>
=> Add HMC package to doc

testcases/OpTestLPM.py
Reverts open-power/op-test#700
=> Revert "Add an option to run single or remote with lpm suite"

testcases/PowerNVDump.py
Now kdump can use the public key exchange method to transfer dump files to the target
machine. This mechanism is enabled for kdump over SSH and NFS
Signed-off-by: Spoorthy S <spoorts2@in.ibm.com>
=> Enable Password less kdump over SSH and NFS

testcases/PowerNVDump.py
Added check for kdumptool command for SLES similar to kdumpctl for rhel.
=> Added check for SLES.

testcases/InstallUpstreamKernel.py
commit 258fb8545f1f: Use grub2-set-default inplace of grubby
switched to using grub2-set-default instead of grubby since
that command is available on most of distributions.
While that command works most of the time, on certain instances
inspite of running that command the kernel boot order is not
set as required. This causes system to boot into a wrong kernel.
Add a check for distro version/release and accordingly use
either grub2-set-default or grubby command
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>
=> testcases/InstallUpstreamKernel: boot order(grub2) fixes

op-test, testcases/OpTestKexec.py
Add new testcase for kexec testing  and support PowerNV in phase1 of development cycle  with different kexec options
=> Enablement of kexec test in op-test framework

testcases/OpTestKexec.py
Modification to "kexec_first_load_then_exec"   where kexec load function modified  by passing argument "l"
Signed-off-by: Sachin P Bappalige <sachinpb@linux.vnet.ibm.com>
=> kexec load function modification by passing argument "l"

testcases/OpTestKexec.py
Linux distros have different naming convention for kernel images. If input images NOT defined in kexec configuration file , then test should consider the base kernel images as shown below. For example :
1) RHEL
vmlinuz-5.x.y.z.ppc64le
initramfs-5.x.y.z.ppc64le.img
2) SLES
vmlinux-5.x.y.z-default
initrd-5.x.y.z-default
3) Ubuntu
vmlinux-5.x.y.z-generic
initrd.img-5.x.y.z-generic
Signed-off-by: Sachin P Bappalige <sachinpb@linux.vnet.ibm.com>
=> Kexec support for SLES and Ubuntu kernel images

testcases/PowerNVDump.py
This test triggers crash while running cpu and memory workload ebizzy.
=> Added testcase to test dump while running workload - v4

testcases/PowerNVDump.py
This kdump/fadump testcase adds two scenarios to check hugepage size after crash
1) with default hugepage size 2MB
2) Set 1GB hugepage size on POWER10 nodes and verify after crash
Signed-off-by: Sachin P Bappalige <sachinpb@linux.vnet.ibm.com>
=> Check  hugepage size with  kdump/fadump 

testcases/PowerNVDump.py
It run makedump file on colleted vmcore and verify output
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>
=> Added makedumpfile test cases

testcases/PowerNVDump.py
This test configures pmem device and dumps vmcore on pmem.
=> Added test to verify dump over pmem device - v3

common/OpTestUtil.py
Logic added to return os name in case of rhel,sles and ubuntu otherwise return unknown
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>
=> Added a library function which return running distro name

OpTestConfiguration.py, common/OpTestEBMC.py, common/OpTestSystem.py
Have some pylint fixes 
Added EBMC stack in op-test which helps to run command via op-test in EBMC based phyp
=> Enable EBMC Phype stack in optest

testcases/PowerNVDump.py
Two scenarios added :
1) kdump/fadump testing with xive=off
2) kdump/fadump testing  with disable_radix
=> Add xive=off and disable_radix testing with kdump

op-test
have define a suite which do
1-enable secure boot
2- run host test case
3- disable secure boot
=> enable guest secure boot as suite

testcases/PowerNVDump.py
Kdump/Fadump testcases  run with different levels of SMT when xive=off
=> Test kdump xive=off with SMT levels

testcases/PowerNVDump.py
Enable different SMT levels for kdump/fadump testing with disable_radix.
=> kdump/fadump  testing for disable_radix with different SMT levels

testcases/InstallUpstreamKernel.py
print the tip of the head for the given repository downloded
=> Capture top commit id for the kernel undertest

testcases/InstallUpstreamKernel.py
Add another parameter commit time and make sure the sha id is full text and not the short one
=> Install: Add commit time parameter and full sha id

op-test
Kdump/Fadump Test cases added to CR 
1) hugepage_checks
2) XIVE_off
3) disable_radix
=> Add  kdump/Fadump testcases to CR list

common/OpTestUtil.py
src rpm will be fetch if src repo is configured
=> Have function which used to get src rpm

testcases/GcovSetup.py
Adding new test for code coverage for distro kernel source.
=> Adding the Gcov support for distro kernel source.

op-test
Adding the test suit to run the gcov and lcov for kernel code coverage on distro kernel source
=> Adding the gcov test suit

OpTestConfiguration.py, common/OpTestHMC.py, testcases/MachineConfig.py
Configuring nx_gzip=1 configures qos_credits. Also added vtpm_version and vtpm_encryption
=> Added nx_gzip config parameter - v2

op-test
Added new kdump/Fadump test cases to CR execution
=> Add additional testcases to CR testing of Kdump/Fadump

common/OpTestHMC.py, common/OpTestUtil.py, testcases/OpTestGSBStaticKey.py
OpTestHMC is added with all the check_APIs related to secureboot testing. This commit addresses the following API additions -
1. check_hmc_level_secureboot_state()
2. check_grub_signature()
3. get_grub_file()
OpTestGSBStaticKey is changed in a way that the above mentioned APIs have been moved to the common area so as to provide generic availibility towards wider usage.
=> OpTestHMC/OpTestGSBStaticKey : align secureboot check-APIs

common/OpTestHMC.py, testcases/MachineConfig.py
Testcase configure hugepages of 2M,1G for Radix and 16M,16G for Hash depending upon user input
=> Added testcase to assign hugepages

testcases/MachineConfig.py
1-Rearranged FLow for CEC setting
2-Rearrange OS config settings
=> Fix config

common/OpTestASM.py
configure_enlarged_io function can be called to enable Enlarged IO on FSP based system.
=> Added API to config parameter to enable enlarged IO.

testcases/MachineConfig.py
Testcase configures number of 16gb hugepages
on CEC as per user input
=> Added testcase to configure 16GB Hugepages- V2

testcases/MachineConfig.py
Rearranged FLow for CEC setting
=> Fix CEC config issue

testcases/MachineConfig.py
Rearranged flow for OsConfig class
=> Fix OS config issue

common/OpTestUtil.py
Change the way to idenfity the PReP partition in single path or multipath environment.
=> Change in identifying PReP partition

.github/workflows/pylint.yml
as recent PR seen as not following pylint so making sure pylint sanity check done of any Pull request
=> enable pylint github Action check for repo

testcases/GcovSetup.py
Added logic to avoid building gcov kernel in case it already configured
=> Added logic to avoid building gcov kernel in case it already configured

common/OpTestUtil.py
added wildcard as :~ as , in couple of system op-test error out as not get exact wild card
=> Fixed login prompt issue as couple of system has new login prompt

testcases/PowerNVDump.py
Moved conditions like when test not able to setup system with desired config it instead of error it should skip
=> Condition FIX: In case of setup issue

common/OpTestUtil.py, testcases/OpTestKernelTest.py
As this function will be used in multiple tests, we can move this function to optest utils
=> Move wait_for function to utils

op-test
=> Added ISST dump coverage

testcases/OpTestKernelTest.py
Made changes to KernelBoot class to add git-bisect for kexec boot on warning.
=> OpTestKernelTest: Git bisect automation for kexec boot failure

testcases/GcovSetup.py
Enhancing script to enable the Gcov on sles distro, taking care of addition kernel config parameter and other dependencies.
=> Adding Gcov enablement for Sles Dsitro to GcovSetup.py

common/OpTestHMC.py
Fixed else: block IndentationError.
=> Fixed IndentationError in common/OpTestHMC.py

common/OpTestHMC.py
Fixed Indentation issue for if else block.
=> Fixed Indentation Error in common/OpTestHMC.py

testcases/PowerNVDump.py
Testcase got failed "service: no such service nfs". we have nfs-server service so updated the same in testcase
=> PowerNVDump.py: Provided fix for nfs service issue

testcases/PowerNVDump.py
This testcase verifies dump collection by passing
junk value to fadump
=> PowerNVDump.py: Added fadump with junk value testcase

testcases/PowerNVDump.py
Testcase passes additional parameter to fadump kernel and verifies it.
=> PowerNVDump.py: Added passing additional param to fadump

testcases/OpTestSecvarctl.py
Added test to build, compile, run secvarctl and generate keys/auth files.
Ran 1 test in 164.866s
OK
Generating XML reports...
Generated XML report: /home/op-test/test-reports/test-run-20250710081144/TEST-testcases.OpTestSecvarctl.SecvarctlTest-20250710081144.xml
=> Added test to build, compile and run secvarctl test.

common/OpTestHost.py, testcases/OpTestKernelDump.py
testcase verifies how many threads has been used for collecting Dump common/OpTestHost.py: Fixed indentation issue
=> OpTestKernelDump.py: Added Multithreading test for Fadump
