open-power/op-test

- common/OpTestIPMI.py
The BVT tests were failing for Open Power Firestone Hardware since the below command was failing
ipmitool -H <BMCIP> -I lanplus -U ADMIN -P admin sdr elist |grep 'OCC Active'
There are 2 OCC chips being Active in Firestone Hardware where as in Habanero LC Hardware, we have 1 OCC chip being Active and hence the sdr elist was not returning the correct values for Firestone Open Power Hardware.
Hence, making this fix in-order to fetch the correct values of 'OCC Active' for both Firestone and Habanero LC Open Power Hardware's.
> Making changes for checking the OCC being Active for Firestone Hardware

- bvt/op-opal-fvt-bvt.xml
- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- ci/source/test_opal_fvt.py
- common/OpTestLpar.py
- testcases/OpTestSensors.py
- testcases/OpTestSwitchEndianSyscall.py
- testcases/__init__.py
1. Hardware monitoring sensors(hwmon driver) using sensors utility
2. Switch endian sys call test which is implemented in linux git repository
For the above two features source files OpTestSensors.py and OpTestSwitchEndianSyscall.py are implemented in common directory
op_ci_fvt.py,test_op_fvt.py : In these files will keep adding new OPAL feature test functions, which are implemented in common directory.
op-fvt-basic.xml : In this xml file calling above test functions inorder to execute the above test functions
op-ci-bmc-run : In this file imported op_ci_fvt, inoreder to invoke the test case.
> Added new test cases for below OPAL features

- common/OpTestIPMI.py
> Removing the redundancy code lines from the ipmi_get_occ_status function

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- ci/source/test_opal_fvt.py
- common/OpTestLpar.py
- testcases/OpTestAt24driver.py
- testcases/OpTestI2Cdriver.py
- testcases/OpTestRTCdriver.py
OpTestRTCdriver.py--->To test Real time clock driver(RTC driver)
OpTestAt24driver.py-->To test Atmel 24 driver(At24 driver)
OpTestI2Cdriver.py--->To test I2C driver
> Adding new test cases for below OPAL features

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- ci/source/test_opal_fvt.py
- common/OpTestConstants.py
- common/OpTestIPMI.py
- common/OpTestLpar.py
- common/OpTestSystem.py
- testcases/OpTestHMIHandling.py
Added below test cases for HMI handling
1. Core checkstop
2. Hypervisor resource error
3. processor recovery done
4. proc_recv_err_masked
And also added ipmi console inetrafces in IPMI, SYSTEM and LPAR libraries.
> Test cases for HMI Handling

- bvt/OPBVTXML.pm
- bvt/OpTestInfra.pm
- bvt/helloworld-include.xml
- bvt/helloworld.xml
- bvt/helloworld2-bvt.xml
- bvt/helloworld2.xml
- bvt/op-ci-basic.xml
- bvt/op-inbound-basic.xml
- bvt/op-it-list
- bvt/read-op-xml-it
- bvt/run-bvt-setup
- bvt/run-op-bvt
- bvt/run-op-it
This patchset goes through and does a *lot* of clean-up in the perl code.
Each change is as self contained as possible, and tries to move us to modern, clean, less error prone perl.
Basic idea is: use Perl modules rather than re-implementing something from scratch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/30)
> Perl cleanup: use modules and clean-up code

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- ci/source/test_opal_fvt.py
- common/OpTestConstants.py
- testcases/OpTestPrdDriver.py
In this test case injecting core FIR errors using xscom utils
and checking whether opal-prd handles it properly in runtime.
Currently injecting error on PBA FIR register.
This we can extend for any number of errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/28)
> Test case for PRD(Processor Runtime Diagnostics) driver.

- bvt/op-outofband-firmware-update.xml
- ci/source/op_outofband_firmware_update.py
- ci/source/test_op_outofband_firmware_update.py
- common/OpTestBMC.py
Fixed the pxssh module import error.
Below is the procedure for FW upgrade through Out-of-band method.
1. Get the current PNOR level before upgrade
2. Clear SEL logs
3. Get current working side-->make sure do fw update on primary side
4. Do ipmi power off.
5. Issue BMC cold reset to bring BMC to stable point
6. Preserve Network settings of BMC
7. Do a code update for both BMC and PNOR firmwares using hpm image method
8. Bring the system up(Power ON)
9. Wait for working state of system
10. Check for any Non-recoverable errors in SEL logs
11. Get PNOR level again after FW Upgrade.
TODO: Gather BMC FW Version info before and after FW upgrade, currently we are getting PNOR version only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> Changed the FW Update script for out-of-band procedure.

- common/OpTestConstants.py
HMI tests are broken due to expecation lists are changed.
Reverting back to correct expectation lists
IPMI_LPAR_EXPECT_PEXPECT_PROMPT_LIST = [r"\[pexpect\]#$", pexpect.TIMEOUT]
a. if command executed without failure we need to expect [pexpect]# .
b. if command fails we are waiting for 500s timeout to capture console log to see any kernel panic or system reboots
this is handled in run_lpar_cmd_on_ipmi_console of OpTestIPMI.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/35)
> Fix for ipmi console execution failures.

- bvt/op-opal-ci-bvt.xml
- bvt/op-opal-ci.xml
- ci/source/op_ci_bmc.py
- common/OpTestBMC.py
- common/OpTestConstants.py
This patch is for flashing pnor images on openpower hardware.
And also this is uesful for flashing both types of images (*.pnor and *_update.pnor).
Note: Assumption is pflash tool available in /tmp directory.
Steps for Host FW(pnor) image flash.
1. check for pflash tool availablity in /tmp directory
2. Do a system ipmi power off
3. Clear SEL logs
4. Transfer PNOR image to BMC busy box(/tmp dir).
5. Flash the pnor image using pflash tool.
6. Bring the system up.
7. Check for any error logs in SEL.
Verified this by testing it on firestone hardware with firestone.pnor and firestone_update.pnor.
Firestone.pnor--------->It will update both side of PNOR Flash storage(Both primary and golden side).
Firestone_update.pnor-->It will update only primary side of PNOR Flash storage.
---
This change is …
> CI for OPAL

- bvt/OPBVTXML.pm
Every so often, the perl interpreter would segfault somewhere in XML::LibXML
This seems to be due to some buggy reference counting in the XML::LibXML
perl module that we hit.
there's a pretty simple workaround though, so let's do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/46)
> fix perl segfault

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- ci/source/test_opal_fvt.py
- common/OpTestConstants.py
- common/OpTestHost.py
- common/OpTestIPMI.py
- common/OpTestSystem.py
- testcases/OpTestSystemBootSequence.py
TestMcColdResetBootSequence.
It has below steps
1. Do a system Power OFF(Host should go down)
2. Set auto reboot policy to off(chassis policy always-off)
3. Issue a BMC Cold reset.
4. After BMC comes up, Issue a Power ON of the system
5. Check for system status and gather OPAL msg log.
TestMcWarmResetBootSequence.
It has below steps
1. Do a system Power OFF(Host should go down)
2. Set auto reboot policy to off(chassis policy always-off)
3. Issue a BMC Warm reset.
4. After BMC comes up, Issue a Power ON of the system
5. Check for system status and gather OPAL msg log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/50)
> Add New Tests for testing system boot sequence.

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- ci/source/test_opal_fvt.py
- common/OpTestHost.py
- testcases/OpTestSystemBootSequence.py
This patch has testcases for testing system power policy
always-off
always-on
previous
And also it has a fix for gathering opal msg logs function(host_gather_opal_msg_log)
which is using commands module, But OpTestHost is not imported commands module.(missed in one of previous patch).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/59)
> Add testcases for testing system power restore policy.

- common/OpTestIPMI.py
got the below error.
SyntaxError: Non-ASCII character '\xe2' in file
op-test-framework/common/OpTestIPMI.py on line 563, but no
encoding declared; see http://python.org/dev/peps/pep-0263/ for
details
To fix the above error need to add 'utf8' encoding
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/60)
> Problem: While encoding the following lines in common/OpTestIPMI file

- bvt/op-ci-bmc-run
- bvt/op-fwts-fvt-bvt.xml
- bvt/op-fwts-fvt.xml
- ci/source/op_fwts_fvt.py
- ci/source/test_fwts_fvt.py
- common/OpTestConstants.py
- testcases/OpTestFWTS.py
This patch adds new Firmware Test Suite tests into the framework, FWTS is test suite which tests firmare basic sanity checks.
Below are the tests added.
bmc_info        BMC Info
olog            Run OLOG(OPAL Log) scan and analysis checks.
oops            Scan kernel log for Oopses.
prd_info        OPAL Processor Recovery Diagnostics Info
This test case works when the corresponding FWTS tool is installed in the ubuntu host OS.
and also olog test assumes that corresponding olog.json file is generated from the skiboot code
into the directory OLOG_JSON_DIR = "/root/skiboot/external/fwts"
And all further fwts tests will be added into this op_fwts_fvt.xml
Signed-off-by: Pridhiviraj <ppaidipe@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Add new FWTS tests.

- bvt/op-occ-fvt.xml
- ci/source/op_occ_fvt.py
- ci/source/test_occ_fvt.py
- testcases/OpTestEnergyScale.py
- testcases/OpTestOCC.py
This patch adds below tests
OCC Reset/Enable/Disable functionality
Energy scale tests(BMC to OCC Interface tests)- dcmi get,set,activate,deactivate power limit.
Note: In order to work Energy scale tests user needs to add corresponding platform power limits
PLATFORM_POWER_LIMIT_HIGH and PLATFORM_POWER_LIMIT_LOW in OpTestConstants.py, because different
platforms has different platform power limits.
Signed-off-by: Pridhiviraj <ppaidipe@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/64)
> Add new OCC and Energy scale tests.

- run
This patch adds support for missing hpm image support for run tool.
By using this one can install full Firmware HPM flash with the help
of op-outofband-firmware-update-bvt.xml
./run --machines op-machines-example.xml --machine firestone3 --hpmimage ~/firmware.hpm --suite op-outofband-firmware-update-bvt.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/66)
> Fix for --hpmimage support.

- bvt/op-ci-basic.xml
- bvt/run-op-it
- ci/source/op_ci_bmc.py
- ci/source/op_occ_fvt.py
- ci/source/op_opal_fvt.py
- common/OpTestIPMI.py
- common/OpTestSystem.py
- run
This pull req gets enough of the test environment/restrict-env working so that when we ./run with --noflash we don't attempt to do a HPM update. Since the HPM update test did a bit of power off/on things, we work around that for --noflash test runs.
This also gets us closer to running on an FSP machine as we exclude the HPM update on non-astbmc based BMCs.
We also mess about with the fun times that is the absence of "Boot Status" on FSP systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/63)
> Get test_env / restrict-env working, enable testing FSP systems

- common/sol_logger.exp
Some BMCs *really* like to randomly drop you off the Serial Over LAN
console. You can get back on it by reconnecting, so this patch changes
our sol_logger to do just that, for up to 10 attempts.
Output will look something like:
EOF detected (3 / 10 attempts)
spawn ipmitool -H fstn5-bmc.ozlabs.ibm.com -I lanplus -U ADMIN -P admin sol deactivate
spawn ipmitool -H fstn5-bmc.ozlabs.ibm.com -I lanplus -U ADMIN -P admin sol activate
[SOL Session operational.  Use ~? for help]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/78)
> common/sol_logger.exp: Reconnect SOL on EOF because BMCs suck

- bvt/op-ci-basic.xml
- bvt/op-opal-fvt.xml
- ci/source/op_ci_bmc.py
- ci/source/op_opal_fvt.py
- common/OpTestBMC.py
- common/OpTestIPMI.py
- common/OpTestSystem.py
- common/OpTestUtil.py
- testcases/OpTestDropbearSafety.py
- testcases/OpTestPCI.py
There are a few cleanups in this patch series, as well as starting to move over individual tests to be run out of the python unittest code, which makes them *much* easier to run on their own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/80)
> Refactor how tests are run, use python unit tests rather than perl/shell wrapper

- bvt/op-occ-fvt.xml
- bvt/op-opal-fvt.xml
- common/OpTestSystem.py
- testcases/OpTestAt24driver.py
- testcases/OpTestDropbearSafety.py
- testcases/OpTestEM.py
- testcases/OpTestEnergyScale.py
- testcases/OpTestFWTS.py
- testcases/OpTestHMIHandling.py
- testcases/OpTestHeartbeat.py
- testcases/OpTestI2Cdriver.py
- testcases/OpTestIPMILockMode.py
- testcases/OpTestIPMIPowerControl.py
- testcases/OpTestIPMIReprovision.py
- testcases/OpTestInbandIPMI.py
- testcases/OpTestInbandUsbInterface.py
- testcases/OpTestMtdPnorDriver.py
- testcases/OpTestOCC.py
- testcases/OpTestOOBIPMI.py
- testcases/OpTestPrdDriver.py
- testcases/OpTestRTCdriver.py
- testcases/OpTestSensors.py
- testcases/OpTestSwitchEndianSyscall.py
- testcases/OpTestSystemBootSequence.py
Some test cases will make the system to not to boot (https://github.com/open-power/op-build/issues/672)
Due to that normal power off/on doesn't bring the system, we were end up in other simpler test cases to fail.
This patch makes existing function sys_bmc_power_on_validate_host to below changes.
if system ping failed---> Do IPMI Power off--->Do BMC Cold reset----> Do IPMI Power ON---> wait for system to boot.
And this sequence will executes only when the system is down and if it is up this function will be just
bypassed.
And this function added in all the test cases begining.
So now we have a effective execution of *most* of the test cases at the cost of *time*
Any new test case addition just use this function at the beginning to execute that test case most of the times.
Still if that …
> Effective execution of all the test cases.

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- testcases/OpTestNVRAM.py
This testcase will run all possible options of nvram tool
to test below functions.
list the partitions/
update config data/
read config data
dump partition data
These will be tested in both Petitboot and host OS.
Signed-off-by: Pridhiviraj Paidipeddi ppaidipe@linux.vnet.ibm.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/82)
> Testcase for accessing NVRAM partition config.

- common/OpTestHost.py
- testcases/OpTestAt24driver.py
- testcases/OpTestI2Cdriver.py
- testcases/OpTestPCI.py
- testcases/OpTestPrdDriver.py
- testcases/OpTestSwitchEndianSyscall.py
It turns out we had both a duplicate host_check_command and we can trivially check for more than one command at once (reducing execution time, although not by much)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/86)
> Improve host_check_command: check more than one command at once

- bvt/op-opal-fvt.xml
- ci/source/op_opal_fvt.py
- common/OpTestHost.py
- testcases/OpTestHMIHandling.py
Running TOD error injection on a 2S machine with a single core
enabled.
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/89)
> Added a varient of TOD error injection test

- bvt/op-opal-fvt.xml
- ci/source/op_fwts_fvt.py
- ci/source/op_occ_fvt.py
- ci/source/op_opal_fvt.py
- common/OpTestHost.py
- common/OpTestIPMI.py
- testcases/OpTestEEH.py
These testcases will tests EEH Error injection testcases.
Note: Some drivers may not have EEH support incase of OpenPower systems.
But this will work effectively in FSP systems, where we have good EEH support.
Currently added execution and gather logs. Checking for actual PCI
recovery is need to add.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/88)
> EEH fencedPHB Error Injection testcase.

- common/OpTestConstants.py
- common/OpTestIPMI.py
- common/OpTestSystem.py
- testcases/OpTestEnergyScale.py
- testcases/OpTestFWTS.py
- testcases/OpTestHMIHandling.py
- testcases/OpTestIPMIReprovision.py
- testcases/OpTestOCC.py
- testcases/OpTestSystemBootSequence.py
In some openpower platforms (example: SuperMicro) there are no
'Host Status' and 'OS Boot' sensors available.
Currently due to above issue below test cases are failing in SuperMicro
Systems
OpTestEnergyScale
OpTestFWTS
OpTestHMIHandling
OpTestIPMIReprovision
OpTestOCC
OpTestSystemBootSequence
So, this patch fixes the above mentioned issue. And also optimized
boot code by adding the API (self.cv_SYSTEM.sys_hard_reboot)
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/97)
> Fixes for enabling the test cases on other non-ibm openpower platforms

- bvt/op-occ-fvt.xml
- bvt/op-opal-fvt.xml
- ci/source/op_occ_fvt.py
- ci/source/op_opal_fvt.py
- common/OpTestHost.py
- common/OpTestIPMI.py
- common/OpTestSystem.py
- run
- testcases/OpTestEEH.py
- testcases/OpTestEM.py
- testcases/OpTestKernel.py
This patch contains below new testcases.
1. Trigger the kernel crash and check system boots fine or not in both
kdump enabled and disabled environments
a. if kdump is disabled
Trigger kernel crash and check for full system IPL
b. if kdump is enabled
Trigger kernel crash and check for crash kernel & full system IPL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/95)
> Add new testcases.

- testcases/OpTestEEH.py
This can significantly reduce run time of tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/102)
> OpTestEEH: split sleep(30) out to poll each second for 30 seconds

- common/OpTestSystem.py
Some kernels display 'kexec_core: Starting new kernel' to indicate
we're doing a kexec, so we should also expect that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/116)
> expect kexec: 'kexec_core: Starting new kernel' also valid

- common/OpTestFSP.py
- op-test
- testcases/KernelLog.py
- testcases/OpTestDumps.py
- testcases/fspresetReload.py
Currently our testcase directly triggers the system dump
even the dump policy for it is disabled, which results in
our testcase won't trigger any system dump and just simply
system IPL's without dumping system files(OPAL, printk, hbrt log)
So this patch fixes this issue by enabling the system dump policy
before triggering any system dump. And also this adds conditions
to retrieve individual files after dump is generated and make
sure the three files(OPAL, hbrt log and printk log) collected
properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/140)
> Fix system dump test case by enabling the dump policy.

- testcases/ConsoleBug150765.py
Make sure IPMI SOL Console connected in another terminal before running this
test. Below is the command line for execution of this test.
./op-test --bmc-type FSP --bmc-ip x.xx.xxx.xx --bmc-username dev --bmc-password ******
--bmc-passwordipmi ***** --host-ip x.xx.xxx.xx --host-user root --host-password *****
--machine-state OS --run testcases.ConsoleBug150765.ConsoleBug150765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/142)
> Testcase for FSP Console Issue(Bug 150765).

- op-test
- New function, addSuites, that will add dict entries to define
additional test suites
- Suite definition and testcase import done in addon setup file
Signed-off-by: Jason Albert <albertj@us.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-test-framework/149)
> Support for addons to define additional test suites

- common/OpTestHost.py
The existing code kind of loop over each cpu file to get pir and takes
too long to discover chip id and core ids.
This patch improves that by gathering all pirs at once. And you don't need to
stare at screen scrolling waiting it to finish collecting all pirs.
Signed-off-by: Mahesh Salgaonkar <mahesh@linux.vnet.ibm.com>
> Optimize the common code that gathers chip id and core id.

- testcases/OpTestHMIHandling.py
In p8 bit 44 of CORE FIR was used to inject Processor recovery masked hmi.
But in p9 bit 44 is no more valid and do not generate Processor recovery
masked hmi. Hence ignore this test for p9.
Signed-off-by: Mahesh Salgaonkar <mahesh@linux.vnet.ibm.com>
> hmi: ignore PROC_RECV_ERROR_MASKED hmi test for p9

- common/OpTestSSH.py
- testcases/SystemLogin.py
Enable run_command to perform sudo commands on the target OS.
Allow commands like 'sudo -s' and other sudo prefixed commands
to automatically pass credentials.
Enables applications and tests to instrument code and test
fixtures for various exploits.
Signed-off-by: Deb McLemore <debmc@linux.vnet.ibm.com>
> Enable OpTestSSH for sudo

- testcases/SecureBoot.py
In P8 platforms ibm,secureboot-v1 uses hash-algo and in P9
platforms ibm,secureboot-v2 uses hw-key-hash-size. So this
patch fixes this accordingly.
> SecureBoot: Fix DT properties check for P8 vs P9

- testcases/InstallHostOS.py
- testcases/InstallRhel.py
- testcases/InstallUbuntu.py
installation script error out , so this patch made some param
as required
failed LOG:
======================================================================
ERROR [1174.995s]: runTest (testcases.InstallRhel.InstallRhel)
----------------------------------------------------------------------
File "/home/praveen/op-test-framework/testcases/InstallRhel.py", line 120, in runTest
self.system.host_console_login()
File "/home/praveen/op-test-framework/common/OpTestSystem.py", line 294, in host_console_login
l_con.sendline(l_user)
File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 1036, in sendline
n = self.send(s)
File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 1024, in send
s = self._coerce_send_string(s)
File …
> Fixed issue in installation when user miss host user name

- common/OpTestHost.py
- testcases/OpTestPNOR.py
On P8 platform:
===============
ID=18           NVRAM 01de2000..01e72000 (actual=00090000)
On P9 plaform:
===============
ID=03           NVRAM 0x00031000..0x000c1000 (actual=0x00090000) [-P--F--]
Not all partitions on P8 platforms having flags, hence make it optional
in regex. So this patch fixes the issue in P8 AMI platforms.
> OpTestPNOR: Fix failure of parsing partitions when flags are optional

- testcases/OpTestHMIHandling.py
cpupower tool won't work with custom upstream kernels, due to which disable
idle states will fail, and hmi tests won't run. This fixes this by falling
back to sysfs based disabling cpu idle states.
And also this reduces the timeout from 120 to 20 seconds as recovery mostly
should happen in very quick.
> OpTestHMIHandling: ensure disable idle states when cpupower fails to do

- testcases/OpTestEM.py
After entering into idle state, a cpu will wakeup in case of a interrupt.
Usage gives number of times a particular state was entered. Thus a cpu
which has more usage may not necessarily have spent more time in idle
state. So time should also be used for monitoring of entering and exiting out
of idle state.
Signed-off-by: Abhishek Goel <huntbag@linux.vnet.ibm.com>
Reported-by: Pridhiviraj Paidipeddi <ppaidipe@linux.vnet.ibm.com>
> OpTestEM : Monitor time as well as usage to test cpuidle driver

- testcases/OpTestEM.py
- testcases/SecureBoot.py
> OpTestEM: Add checks for WoF support by looking at DT properties

- testcases/OpTestEM.py
> OpTestEM: Remove redundant tear_down function.

- common/OPexpect.py
- common/OpTestIPMI.py
- common/OpTestSSH.py
- common/OpTestSystem.py
- testcases/Console.py
- testcases/SecureBoot.py
- testcases/TrustedBoot.py
Auto detect the current state of the machine.
When performing tests the current state of the machine
will be checked to transition to the desired state
requested by the test fixture.
This relates to the --machine-state command line option,
instead of having to manually identify the --machine-state
the detection will query the current machine to
see if it can be determined if at Host OS or Petitboot.
If not able to determine the current state then proceed
as usual by entering UNKNOWN machine state.
Signed-off-by: Deb McLemore <debmc@linux.vnet.ibm.com>
> OpTestSystem: Detect machine state

- op-test
- testcases/Petitbooti18n.py
Basic sanity check to ensure unicode strings are correctly displayed.
Starts to resolve https://github.com/open-power/op-test-framework/issues/164
From here we would switch the configured language and ensure the correct
unicode strings are present elsewhere in the UI.
> Petitbooti18n: Check i18n strings are displayed

- op-test
- testcases/IplParams.py
iplparams will control certain system fatures to be enabled or disabled
These are controlled and initialized by hostboot during IPL time. So
linu/OPAL will enable/disable the feature accordingly. These will be
under /ibm,opal/fw-features/ device tree node with a property under each
node(either enabled or disabled)
So this testcase will verify each of them as per expectation.
> Add testcase to verify fw-feature's which set during IPL time

- testcases/I2C.py
All kernel features may not available in petit kernel, hence don't
check for i2c_adapter class.
> I2C: Fix failure of i2c adapter detection in petit kernel

- common/OpTestIPMI.py
- common/OpTestSSH.py
Currently we are printing any running commands two times.
This fix will make sure only the running command shows on
console any additional prints will be blocked.
> OpTestSSH/IPMI: Fix printing command two times

- OpTestConfiguration.py
- README.md
Example output:
===============
ls test-reports/test-run-20180608101142/
20180608101142.log
TEST-testcases.OpTestFlash.FSPFWImageFLASH-20180608101142.xml
Kernel_dmesg_log_Fri_Jun__8_10:12:10_2018.log
TEST-testcases.OpTestFlash.OpalLidsFLASH-20180608101142.xml
Opal_msglog_Fri_Jun__8_10:12:09_2018.log
TEST-testcases.OpTestFlash.PNORFLASH-20180608101142.xml
TEST-testcases.OpTestFlash.BmcImageFlash-20180608101142.xml
TEST-testcases.OpTestSensors.OpTestSensors-20180608101142.xml
> conf: Enable test reports store in a new directory per test run.

- common/OpTestInstallUtil.py
- osimages/hostos/hostos.ks
- osimages/rhel/rhel.ks
- osimages/ubuntu/preseed.cfg
The --proxy option is not populated to the kickstart/preseed files when
installing an OS; update the relevant files to recognise the variable.
> OpTestInstallUtil: Set proxy variable in script files

- common/OpTestSSH.py
On afs LCB setup SSH is a patched version of ssh which blocks the
ssh connection due to afs token passing. Below is the failure signature
Received disconnect from x.xx.xxx.xx: 2: Invalid ssh2 packet type: 192
To fix this issue pass afstokenpassing=no to ssh command. But this will
throw a below warning message on other non afs machines.
command-line line 0: Unsupported option "afstokenpassing"
> OpTestSSH: Fix SSH connection failure on afs LCB setup.

- common/OpTestBMC.py
Fixes: https://github.com/open-power/op-test-framework/issues/250
> OpTestBMC: like SSH don't use public key authentication for rsync

- OpTestConfiguration.py
Currently the op-test primary-config (~/.op-test-framework.conf) is
read after reading the secondary-config mentioned on the command line
via '--config-file' arg. This prevents options set in secondary-config
to override the options set in the primary-config. For e.g:
Primary-config:
bmc_username=sysadmin
Secondary-config:
bmc_username=myuser
Value used in code:
bmc_username == 'sysadmin'
This patch updates the read order of the configurations so that
secondary-config is read after the primary-config. This makes it
possible for secondary-config to override values previously defined in
primary-config and enforce this more intuitive precedence order:
cmd-line-options > secondary-config-options > primary-config-options
With this change the value for variable bmc_username == 'myuser' for
the …
> Read secondary config after primary config

- OpTestConfiguration.py
Presently if the secondary config (specified via --config arg) doesn't
exist a very misleading and confusing error message is shown:
ERROR: runTest (testcases.OpTestFlash.OpalLidsFLASH)
----------------------------------------------------------------------
<snip>
raise SSHSessionDisconnected("SSH session exited early!")
SSHSessionDisconnected: SSH session/console disconnected due to 'SSH session exited early!'
This is due to SafeConfigParser.read() function that doesn't report an
error in case the input file-path doesn't exists. This patch fixes this
by adding a existence check for secondary config so that a more
relevant error is reported to the user.
Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>
> Fail early if secondary config doesn't exists

- testcases/OpTestFlash.py
- testcases/OpTestMtdPnorDriver.py
Commit 53e7078c changes number of argument to copyFilesToDest().
Fixes: 53e7078c (EnergyScale_BaseLine: port to op-test)
> Fix copy to destination function

- testcases/OpTestRebootTimeout.py
Useful for tracking the time we're losing between calling reboot and
actually rebooting.
> TestReboot: Test time to complete reboot call

- testcases/OpTestPCI.py
Initial PCI link problem detection - testing link speed&width are
running optimally
Hi Stewart, this is just a draft of the PCI link problem detection test. Can I please get some feedback on this? Thank you!
It runs lspci and then collects all of the relevant data into a list of Device objects (device_list). It then iterates over the list, checking for links between other devices and then testing if those links are running at the speeds/widths matching the capability.
> Initial PCI link problem detection

- common/OpTestSystem.py
- testcases/OpTestRebootTimeout.py
Set loop_max to allow for enough time for SBE Update.
Cleanup removal of host_console_login and host_console_unique_prompt.
> OpTestSystem: Increase loop_max for SBE Update

- common/OpTestASM.py
Added a function to start a virtual tty debug session for the given timeout,
paritionid and sessionid, this will help in tests which requires to run phyp
commands
> start_debugvtty_session: function to create debug vtty session

- common/OpTestHost.py
Enable host_check_command to take both args and kwargs.
> OpTestHost: Fix host_check_command arguments

- OpTestConfiguration.py
- OpTestLogger.py
- common/OpTestBMC.py
- common/OpTestIPMI.py
- common/OpTestOpenBMC.py
- common/OpTestSSH.py
- common/OpTestSystem.py
- common/OpTestUtil.py
- op-test
- testcases/OpTestExample.py
- testcases/OpTestFlash.py
Provide a common logger (with file like methods) for op-test.
Provide a main log file for summary information.
Provide a debug log file for more verbose information to assist
during testcase development and testcase result analysis to
assess errors and failures and allow testcase instrumentation
to be non-obstructive to the main log file consumer.
Provide a mechanism to capture traces (adding debug loggers).
See OpTestExample.py for sample module instrumentation.
> OpTestLogging: Add python logger infrastructure

- OpTestLogger.py
> Fix adding random newlines inserted in the debug log for pexpect

- common/OpTestSystem.py
Raise an UnexpectedCase and go to UNKNOWN_BAD if we see a skiboot abort, as
signalled by the string "Aborting!"
Closes: #290 ("OpTestSystem should die earlier on skiboot aborts")
Signed-off-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>
-------------------------
This is my first time contributing to op-test-framework, I copied the callback from guard_callback() but I'm not sure whether the message or the exception are the most appropriate for this case. Feedback welcome!
> OpTestSystem: Stop IPL when skiboot abort detected

- common/OpTestQemu.py
Recent updates to Cedric's powernv Qemu model (which is what we're
realistically running) change how devices must be attached.
Three PHBs are initialised by default but no default PCI layout is
provided[0]. This leaves us with one free slot on each PHB to use.
This can be expanded by adding bridges but for our current uses we
only need two slots, one for the scratch disk and one for the CDROM.
[0]: https://github.com/legoater/qemu/wiki/PowerNV#branch-powernv-30
> OpTestQemu: Fix disk/cdrom attach

- OpTestConfiguration.py
- common/OpTestQemu.py
- op-test
- testcases/OpTestFlash.py
Support attaching a PNOR image to the QEMU instance, and bring OpTestQemu in to line with the logging changes.
> OpTestQemu improvements - host PNOR & logging

- common/OpTestIPMI.py
- testcases/OpalSysfsTests.py
As the fix for powercap setting through inband ipmi went into
a BMC release. So we can remove those enable/disable sensor
polling workarounds.
> opal_powercap: Remove workarounds around power cap tests

- common/OpTestHost.py
Add optional source, destination path args to copy files
to host method
> Add optional source, destination path args to copy to host

- common/OpTestHost.py
Current test for existence of a CAPI fpga card only includes a single
Nallatech card and ignores other CAPI cards in the system. So this
change updates OpTestHost.host_has_capi_fpga_card() to also include
other CAPI compatible cards by performing lspci for PCI devices with
IBM vendor id (0x1014) and device class as 'Processing
Aaccelerator' (0x1200).
Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>
> OpTestHost: Update test for existence of CAPI card

- OpTestConfiguration.py
- common/OpTestQemu.py
- op-test
This series contains a few minor fixes for issues with initial op-test deployment with qemu;
the ability to stop on the first failure (with `--failfast`), and slightly better error reporting when
pexpect can't start the qemu process.
> Minor UI improvements

- common/OpTestQemu.py
Currently if the Qemu command fails early op-test will loop for a while
trying to "reconnect" by running the command again. If Qemu has failed
this early however it's most likely due to an error in the qemu options
or some internal Qemu error and there's no point waiting for it to fix
itself.
Check the status of the command in connect() and raise a CommandFailed
exception if it has failed immediately. Also remove the reconnect loop
in get_console() as it is not useful.
> OpTestQemu: Fail test if Qemu command fails

- common/OpTestIPMI.py
Fix the naming syntax for the module imported
> OpTestIPMI: Fix syntax for module import usage

- OpTestConfiguration.py
- testcases/DeviceTreeValidation.py
FSP IPMI commands do not need UID, so remove from ipmitool usage.
OpTestConfiguration exception handling improvements to catch for release on reservations.
Use host console object for host methods for DeviceTreeValidation testcases.
> OpTestConfiguration: Allow FSP IPMI commands

- common/OpTestInstallUtil.py
- testcases/OpTestFlash.py
Currently for fsp platforms we have pre-assumed the host n/w is
configured in petitboot. To remove this pre-requiste re-use
configure_host_ip function from OpTestInstallUtil to configure
the host n/w during runtime before downloading firmware image.
> flash: configure host n/w before downloading firmware image

- common/OpTestThread.py
- testcases/RunHostTest.py
1) Fix OpTestThread: Minor fixes for OpSolMonitorThread3
Patch has the following minor fixes
a) OpSolMonitorThread3 has an unused log_file
b) Use get_console() to re-initiate console access
2) RunHostTest: Monitor console on running host commands
This patch adds support to monitor console when running host command(s).
>  RunHostTest: Monitor console on running host commands

- common/OpTestQemu.py
Missed a change of sol variable name to pty.
> OpTestQemu: Fix variable name missed pty

- OpTestConfiguration.py
- common/OpTestInstallUtil.py
- op-test
- testcases/OpTestKernelArg.py
1. Introduce API to update kernel cmdline option and reboot that can be used from tests.
2. support for kernelcmdgroup parser to provide `--add-kernel-args` and `--remove-kernel-args`.
3. OpTestKernelArg test to bringup host with updated kernel cmdline option by adding/removing/both.
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
> OpTestKernelArg: add/remove kernel cmdline options

- common/OpTestThread.py
Fix typo for get_console() function
> Fix re-connecting console thread

- OpTestConfiguration.py
- common/OpTestMambo.py
- common/OpTestSystem.py
- common/OpTestUtil.py
- skiboot.tcl
- testcases/Console.py
- testcases/DPO.py
- testcases/FWTS.py
- testcases/OpTestInbandIPMI.py
- testcases/OpTestMamboSim.py
- testcases/Petitbooti18n.py
- testcases/SystemLogin.py
Integrate Mambo simulator to provide mechanism to run op-test testcases.
Need to have a mambo binary, --mambo-binary, defaults to
/opt/ibm/systemsim-p9/run/p9/power9.
Need to configure --bmc-type mambo, --flash-skiboot (skiboot.lid) and
--flash-kernel (zImage.epapr or vmlinux) and conditionally
--flash-initramfs.
> OpTestMambo: Integrate Mambo

- testcases/DeviceTreeValidation.py
goto_state first to allow test to operate even when machine starts
powered off.
> DeviceTreeValidation: GoTo proper state for tests

- common/OpTestHost.py
> OpTestHost: discriminate between OpenCAPI and CAPI cards.

- testcases/FWTS.py
Add QEMU to the catch on skipping test.
> FWTS: Catch QEMU exception to skip test

- testcases/IplParams.py
Skip test on QEMU/Mambo, following file does not exist:
/proc/device-tree/ipl-params/sys-params/elevated-risk-level
> IplParams: Skip for QEMU/Mambo

- testcases/OpTestPNOR.py
Fix KeyError for flags when they do not exist.
> OpTestPNOR: Fix KeyError for flags

- op-test
AES/Hostlocker providing default values for credentials and other
parameters can trigger unexpected workflows.
Clarify the message to help the user determine what to adjust to make
the tests work.
During op-test suite setup the InstallHost class triggers the flow.
> InstallHost: Unexpected configuration

- common/OpTestSystem.py
- testcases/BasicIPL.py
With HIOMAP we had a bug where things would go poorly if you rebooted the BMC and then rebooted the host.
So, let's add a test.
> Bmc reboot then host reboot

- OpTestConfiguration.py
- common/OpTestSystem.py
- common/OpTestUtil.py
Dump out the firmware versions being tested at the conclusion of the run.
> OpTestUtil: Dump Firmware Versions Tested

- OpTestConfiguration.py
- op-test
Add the args to the debug log to aide in problem determination.
Additionally dump the conf file to debug log as well for later use.
> op-test: Add argv to debug logs

- op-test
- testcases/gcov.py
This is an interim solution until we can do this magically by obvserving
a state transition request and going "oh, we need to pull gcov data".
But, this commit will pull into the test run log directory a dump of the
gcov data from skiboot for both the skiroot and host suites. With this
we can get a code coverage report of what code is being covered by
op-test.
> Pull gcov data at end of skiroot and host test runs

- README.md
Add python modules for unittest and xml reporting.
> README: Add python modules for unittest and xml

- op-test
Temporarily disable tests to achieve automation in various
build levels.
> op-test: Temporary test removals

- common/OpTestFSP.py
> FSP machines don't support IPMI SEL or IPMI DCMI

- op-test
Set the exit_code for test errors and test failures so the proper
exit_code is returned upon exit (the newly added finally clause runs
which needs to pick up the proper exit_code in case exceptions are
thrown during the test runs).
> op-test: Fix exit_code

- op-test
- testcases/OpTestFlash.py
This properly sets exit_code for the only_flash path,
as well as fails the test (instead of error).
> OpTestFlash: Fail test when unable to open tar

- op-test
Update only_flash message as INFO instead of ERROR.
> op-test: only_flash INFO message

- testcases/OpTestInbandIPMI.py
When printing directly to stdout, the XML runner will capture the stdout
cumulatively and this shows up in all subsequent XML files which may appear
odd to the consumer looking at non-related XML files.
This info can also appear as noise in other stdout captures.
/usr/local/lib/python2.7/dist-packages/xmlrunner/result.py
line 276 _save_output_data
> OpTestInbandIPMI: Log failure info to debug logs

- common/OpTestUtil.py
When flashing systems with limited shell we get various
messages, so make the filter more generic to catch more variations.
> OpTestUtil: Generalize the lsprop filtering

- common/OpTestSystem.py
Reduce the kill_cord ceiling to a reasonable time to allow tests
to stop when not being successful in booting.
> OpTestSystem: Reduce kill_cord ceiling

- common/OpTestUtil.py
Exception path on logout needs to not reference r.
> OpTestUtil: Exception handling

- README.md
Found a bug in the pip install xmlrunner where failures were being
reported as errors.
While investigating where to submit the fix it seems that
unittest-xml-reporting is the proper python package
which properly reflects failures and errors.
To document the problem found if installed the pip xmlrunner:
line 184 /usr/lib/python2.7/site-packages/xmlrunner/xmlrunner.py
testinfo = _TestInfo(self, test, _TestInfo.ERROR, err)
self.errors.append((
should be:
testinfo = _TestInfo(self, test, _TestInfo.FAILURE, err)
self.failures.append((
So we update op-test README to only suggest unittest-xml-reporting
> README: Remove old xmlrunner

- op-test
When an unknown suite name is input, provide log traces available
to help determine the issue.
> op-test: Provide helpful info when suite not found

- testcases/OpTestFlash.py
When the PNOR/BMC file does not exist, error the test to allow
automation/scripts to get the proper exit code.
> OpTestFlash: Fail PNOR/BMC flash when file not there

- .travis.yml
- ci/build-qemu-powernv.sh
- testcases/OpalMsglog.py
Pulling palmetto.pnor from openpower.xyz, we can run the full qemu suite as part of travis-ci, and thus for our pull requests as well.
> Run qemu suite as part of travis-ci

- testcases/BasicIPL.py
When EOF encountered we need the pexpect imports.
> BasicIPL: import pexpect for EOF

- testcases/InstallRhel.py
- testcases/InstallUbuntu.py
Since op-build 61d9a2ee4af05e139d57bbb848ef9bdceac5d58e we won't get
the 'Sent SIGKILL to all processes' message on the console. So, we
should look for the sign that kexec is doing something as well.
> Install OS: Look for 'Starting new kernel' for kexec occuring

- testcases/gcov.py
Skip the testcase which helps construct code coverage reports
if skiboot is NOT built with GCOV enabled.
> gcov: Skip test if not a gcov build

- testcases/OpTestInbandIPMI.py
Disable for now some dcmi commands, unreliable at best.
> OpTestInbandIPMI: Disable dcmi power reading

- op-test
Add test suites which identify tests to be run on a per-commit
or pull-request basis.
Idea being that the CI will run the desired suite and as the
content of the suite needs to be updated that can be done
without changing the externals for the CI jobs.
> op-test: Add test suites for per-commit and pull-request

- common/OpTestSystem.py
In some cases, kernel booting would drop down to
dracut console, this patch would detect that
state and properly errorout the testcase.
> Add support for dracut detection during boot

- testcases/NX842.py
Create a small filesystem on a zram device, checking we appear to use the
NX device.
We don't really have a good way as of yet to ensure we actually end
up using the hardware rather than the software though.
This should be enough for a smoke test however.
> NX842 compression test using zram

- common/OpTestSSH.py
OpenBMC systems use ssh for console access, So we will hit
with below issue, let's extend custom logger support
to ssh connection to fix this issue.
```
File "./op-test-framework/testcases/RunHostTest.py", line 51, in setUp
self.console_thread = OpSOLMonitorThread(1, "console")
File "./op-test-framework/common/OpTestSOL.py", line 62, in __init__
self.c = self.system.console.get_console(logger=self.logger)
TypeError: get_console() got an unexpected keyword argument 'logger'
```
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
> Fixup: Add custom logger support for ssh connection

- common/OpTestSystem.py
- common/OpTestUtil.py
When we are unable to properly search the pty buffer for expected
strings, we perform a recovery path.  When this recovery path
is performed we need to get a new console object to properly
continue operations.
> OpTestSystem: Recover lost sys_pty

- testcases/IplParams.py
Skip the tests if processor is not GA level.
> IplParams: Skip test if non-GA processors

- testcases/OpTestFastReboot.py
Unittest SkipTest throws an exception when passing null at end of string
which subsequently produces malformed XML when parsed by plugins.
> OpTestFastReboot: Remove devicetree strings from format

- testcases/FWTS.py
On RHEL ppc64le there is not an RPM package so the FWTS code is
cloned and installed locally, so add PATH to allow proper
search for binary.
> FWTS: Add PATH for RHEL

- common/OpTestUtil.py
Add the log location at the end of the op-test run so its helpful
to know which directory the current run is dumping logs,
especially helpful if running multiple sessions with long output.
> OpTestUtil: Add log location at end of run

- testcases/OpTestOCC.py
When run_commands fail, catch the exception to fail the test.
> OpTestOCC: Catch exceptions to fail test

- common/OpTestSSH.py
- common/OpTestSystem.py
- common/OpTestUtil.py
Add some debug tracing to aide during problem determination
for pexpect pty buffer management.
When the pty object gets closed, dies, or some other state that
renders the pty object not usable, then the old pty buffer and sockets
get closed and any data waiting or pending on the old socket is lost.
A new pty object is created (new pexpect spawn of pty process, etc)
and this new process and new buffer are empty upon creation.
Until new data arrives on this new pty object buffer there is nothing
to be read.  The application writer (you!) will need to either kick
something in the new buffer or know that some future action will
pipe data to the new socket so that things are not hung (timing issues
can make this unpredictable), so its best that an explicit action
occurs, e.g. sendline "date". …
> OpTestSystem: Aide PTY tracing

- testcases/RunHostTest.py
Patch fixes a recent change in SOL thread monitor causing an error for starting a thread
> Fix thread monitoring in RunHostTest

- OpTestConfiguration.py
- common/OpTestOpenBMC.py
Download the openbmc dumps to logdir to allow for running
--run testcases.testRestAPI.HostOff.test_obmc_download_dumps
(possibly as an additional component of automation).
Additional issue opened on openbmc:
BMC Capture journal ->
https://github.com/openbmc/phosphor-debug-collector/issues/6
> OpTestOpenBMC: Download dumps to logdir

- common/OpTestOpenBMC.py
- common/OpTestUtil.py
New OpenBMC bmcweb is *different*
We need to enable session cookie as well as
update URL's and syntax which is less tolerant.
From Matt Spinler:
Other differences I've noticed from phosphor-rest:
* URLs are case sensitive
* Will not interpolate strings to ints
e.g. won't covert "1000" to 1000 if D-Bus arg is an int
* Not tolerant on things like double '/'s in the URL
e.g. /xyz/openbmc_project//attr/blah... will not work
> OpTestUtil: Enable for bmcweb

- testcases/OpTestPNOR.py
Add a retry for commands in case SOL connections (typically) may
encounter some glitches.
> OpTestPNOR: Add retry

- common/OpTestBMC.py
If the user has an SSH key installed on the BMC rsync won't prompt for a
password and the expect logic will fail. Rearrange it slightly so that a
password prompt isn't mandatory.
> OpTestBMC: Don't error if password not required

- testcases/DeviceTreeWarnings.py
We have fixed xscom/mcbist* related device tree warnings in upstream skiboot.
Lets remove mcbist* entry from filter list.
-Vasant
> DeviceTreeWarnings: Remove mcbist from filter list

- common/OpTestUtil.py
Checks if we're already root in get_sudo() and exits early if so. This avoids issues with multiple sub-shells in Petitboot and otherwise shouldn't have an effect since the prompt should already be set up.
Probably a good idea to merge after the Skiboot v6.2.x branch receives the required backport for QEMU CI to run to make sure I haven't found a new corner case :)
> Add check for root in get_sudo(), and some cleanups

- OpTestConfiguration.py
- common/OpTestIPMI.py
- common/OpTestOpenBMC.py
- op-test
Cleanup a few places where the logfile abstraction parameters need
to be filtered to the various classes to have the logs capture as
appropriate.
> OpTestConfiguration: logfile abstraction cleanup

- common/OpTestInstallUtil.py
- common/OpTestSystem.py
- common/OpTestUtil.py
- testcases/InstallRhel.py
- testcases/InstallUbuntu.py
- testcases/gcov.py
Validate configuration parms to setup the IPs.
Add error handling for socket connections and add
some retry logic/handling.
> OpTestInstall: Network config and timing

- testcases/OpTestEM.py
Skip testcase 'cpu_boost_freqs_host' which tests the WOF range
frequencies when 'stop5' idle state is not enabled on the system.
Signed-off-by: Shilpasri G Bhat <shilpa.bhat@linux.vnet.ibm.com>
> OpTestEM: Check for stop5 for WOF test in POWER9

- testcases/OpTestInbandIPMI.py
Pass the test if SEL has no entries is returned.
> OpTestInbandIPMI: Pass on SEL no entries

- op-test
> op-test: Add missing testcase imports

- testcases/SbePassThrough.py
Need to confirm the pid of opal-prd to assure it stayed
running before running tests.
> SbePassThrough: Verify opal-prd running

- common/OpTestInstallUtil.py
- testcases/OpTestFastReboot.py
There's been some reports of some issues with SRESET on POWER8 while the
host is under load.
This is an attempt to test for any such problem by using the 'stress'
utility to produce some workload on the host and then do fast reboot.
Currently this appears to work okay on POWER8, so work on locating the
bug is ongoing.
> Add FastRebootHostStressTorture: test fast-reboot while host is stressed

- common/OpTestUtil.py
Commit 33f9a4b "Check if already root before trying sudo" added an early
check for root but misinterpreted how check_root() would fail. Update
check_root() to explicitly return whether or not the current user is
root.
> OpTestUtil: Properly handle check_root() failure

- op-test
- testcases/BootTorture.py
- testcases/OpTestPCI.py
Enable the ability for each test to be run based on a subclass
setup.
Enable dynamic comparision of hardboot skiroot to hardboot host os
and softboot skiroot to softboot host os.
Add a pci-regression suite which performs full coverage.
> OpTestPCI: Refactor classes for reuse

- common/OpTestIPMI.py
Add some debug tracing to aide during problem determination
for pexpect pty buffer management.
> OpTestIPMI: Aide PTY tracing

- common/OpTestSystem.py
> OpTestSystem: Simplify kernel grep

- OpTestConfiguration.py
- testcases/InstallUpstreamKernel.py
Let's boot newer compiled upstream kernel using
kexec if --use-kexec boolean param is set by user,
which would help during boot failures of newer compiled kernel,
as reboot of host would boot bydefault to previous host kernel.
and optionally append kernel commanline using
--append-kernel-cmdline string param.
Fixes: #367
> Add kexec support for upstream kernel Install test

- OpTestConfiguration.py
- common/OpTestMambo.py
The default timeouts for things are already pretty liberal, but
functional simulators are *incredibly* slow, especially when running on
shared hardware.  Add a new configuration option that (by default)
doubles all timeouts, and allow users to expect things to be even slower.
Signed-off-by: Russell Currey <ruscur@russell.cc>
> mambo: Multiply all timeouts by a user-defined factor

- testcases/Console.py
and fall back to ctrl-z then killing things.
AT least a simple work around until https://github.com/open-power/op-test-framework/pull/463 or the root cause and fix is in.
> Console: Attempt to recover from ctrl-c failing

- OpTestConfiguration.py
- common/OpTestQemu.py
- common/OpTestUtil.py
When exit path is via optest_handler (via a signal) we need to
cleanup the temp disk file created and/or opened.
Add the qemu_scratch_disk to the cleanup routine.
Add a new qemu_scratch_disk option (overloading the
host_scratch_disk does not allow for proper handling
since the Install* tests require other parameters) and
we need the temp or consumer provided qemu_scratch_disk
to properly close.
> OpTestQemu: Cleanup temp disk file

- common/OpTestSSH.py
- common/OpTestSystem.py
- common/OpTestUtil.py
Commit 97b808e3 "OpTestSystem: Improve Petitboot transitions" made
several improvements to reliably dealing with the Petitboot menu. Part
of this was using Ctrl-C to exit the UI. While this is better for making
sure the UI is exited, it drops the system to a less functional shell
than the one normally started by exiting Petitboot normally.
Return to using 'x' to exit the UI but properly this time and with a bit
more paranoia. Instead of using sendline() or Ctrl-C to drive output,
use Ctrl-L and handle the extra 'erase' character that frustrated
previous efforts at its use. In petitboot_exit_to_shell() an 'x' is sent
on each attempt to gain the prompt in case the system is currently in a
Petitboot submenu.
This maintains reliability when dealing with the Petitboot state and
avoids issues …
> common: Improve Petitboot detection and shell exit

- OpTestConfiguration.py
Otherwise, if using a shallow clone without tags present (common
in jenkins setups), we're not going to get what version is being used.
> Use git-describe --always to get op-test version

- testcases/OpTestHMIHandling.py
The commit 4fd2225 mistakenly disables HMI tests for Power8. This is
because the 'else' condition got under wrong 'if'. This patch fixes that.
Fixes: 4fd2225 ("OpTestHMIHandling: opal-gard interactive support")
Signed-off-by: Mahesh Salgaonkar <mahesh@linux.vnet.ibm.com>
> OpTestHMIhandling: Fix the HMI handling for Power8

- OpTestConfiguration.py
- common/OpTestFSP.py
- common/OpTestHMC.py
- common/OpTestSOL.py
- common/OpTestSystem.py
- common/OpTestUtil.py
- testcases/RunHostTest.py
Add HMC utility functions for PHYP type machines
This patch adds changes to handle PHYP based machines using HMC
command line. The following are the utility provided in the patch
HMC utility functions to
1) Power on/off Managed System
2) Power on/off LPARs
3) Provide LPAR console object
4) Run commands on LPAR with console support
> Support for PowerVM based HMC console

- OpTestConfiguration.py
In some situations the file system may not allow the git
describe --always to cross file system boundaries
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)
Ignore the failure and just log that we tried.
> Catch git describe failure

- op-test
`InstallRhel` test can be reused to install Fedora from target
os repo.
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
> op-test: include fedora to be considered for installation

- common/OpTestBMC.py
- common/OpTestOpenBMC.py
- testcases/OpenBMCReset.py
This patch adds tests to verify OPAL - BMC interface.
- BMC reboot vs Host reboot
- BMC reboot vs Host shutdown
- BMC reboot vs Host tests
-Vasant
> [OpenBMC Torture] This test cases tests OpenBMC - OPAL interface

- osimages/rhel/rhel.ks
automated installation gets interrupted if packages are not available
and asks for user input, instead continue the installation.
```
The following packages are missing,
packages name
;; ;;
Would you like to ignore this and continue with installation? Please respond 'yes' or 'no':
```
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
> rhel.ks: add `--ignoremissing` avoid interruption if packages are missing

- common/OpTestUtil.py
When logging into the host OS out-of-band (eg. IPMI) the login prompt
does not respond to Ctrl-L as expected. If we know we're waiting for a
host login prompt (eg. we know the state or we're booting up from
Petitboot), trigger a proper refresh by hitting enter at the prompt.
> OpTestUtil: Trigger refresh of host login prompt

- testcases/PciSlotLocCodes.py
things may have a loc-code but no slot name.
e.g. a switch on the planar.
> PciSlotLocCodes: permit loc-code but no slot-name

- op-test
The Console32k test is buggy and seemingly fails at random, and it also
takes a long time.  In mambo the objective isn't to test the "BMC", so
it doesn't make sense to include the test.
> mambo: Disable Console suite in Mambo

- common/OpTestSystem.py
Similar to b8629a8 "OpTestUtil: Trigger refresh of host login prompt"
the same problem is present in detect_target(). detect_target() is
called in a loop from run_DETECT() - if it fails to detect a state the
first time, send a carriage return to force the host login prompt to
print since it doesn't respond to Ctrl-L.
Additionally if detect_target() fails to detect a state it increments
detect_counter, however the loop in run_DETECT() also does this and the
detect loop only ever executes once. Remove the increment in
detect_target() and leave it to run_DETECT().
> OpTestSystem: Force prompt refresh if unresponsive in detect_target

- op-test
- testcases/PetitbootMMU.py
We expect the petitboot kernel to always use hash MMU on Power9. This
test case will also test that Power8 is using radix.
It uses /proc/cpuinfo while booted into the petitboot environment.
Signed-off-by: Joel Stanley <joel@jms.id.au>
> Add check for the MMU type under petitboot

- OpTestConfiguration.py
- common/OpTestSystem.py
- common/OpTestUtil.py
Skiboot parses configuration options in NVRAM at boot time which affect
runtime behaviour, and several of these can be potentially dangerous or
detrimental. When possible check NVRAM for any Skiboot configuration
options and warn about them and the end of the test run.
Fixes #492
Example:
2019-05-10 13:42:57,768:op-test.common.OpTestUtil:dump_nvram_opts:WARNING:
2 NVRAM debugging options set
These may adversely affect test results; verify these are appropriate if a failure occurs:
----------------------------------------------------------
bootargs=modprobe.blacklist=amdgpu
test-cfg=test-value
----------------------------------------------------------
> Check Skiboot NVRAM options before testcase

- common/OpTestQemu.py
- testcases/Petitboot10000Disks.py
The powernv QEMU model only has 3 free slots which doesn't leave a lot of room for tests that want more complicated setups. Instead fill each of these slots with a PHB which we can insert further devices into.
This also extends the scratch disk concept to support an arbitrary number of disks. The Petitboot10000Disks testcase provides an example of this functionality. The intended use case for this is to extend the Petitboot testcases to test against different source devices, filesystems, and configuration formats.
For particularly ambitious testcases the QEMU setup will also dynamically insert more PHBs into the model to support an arbitrary number of devices.
As a bonus fix the NIC setup so that we can properly use it in powernv with a consistent MAC address.
> OpTestQemu: Better PHB handling, multi-disk setups, proper NIC support

- testcases/InstallUpstreamKernel.py
While using op-test to build and boot an upstream kernel on a P9 box,
grubby --set-default command does not reliably work (atleast in my CI
environment) on every instance. A lot of time machine fails to boot kernel
and drops to petitboot shell possibly due to to corrupted grub2 boot loader.
Only way to recover the machine is by running grub2-mkconfig command manually.
This patch changes the order of grub2-mkconfig and grubby commands to
ensure default kernel boots successfully.
Signed-off-by: Sachin Sant<sachinp@linux.vnet.ibm.com>
> InstallUpstreamKernel: Change execution order for grubby and grub2-mkconfig commands

- common/OpTestQemu.py
Qemu expects a name of the 'bios' and the path to be passed in separate
options:
-L  path
Set the directory for the BIOS, VGA BIOS and keymaps.
To list all the data directories, use "-L help".
-bios file
Set the filename for the BIOS.
This uses the same config option, but splits out the path and filename
components.
Signed-off-by: Joel Stanley <joel@jms.id.au>
> qemu: Allow setting of path and filename

- common/OpTestHMC.py
dumprestart_lpar and restart_lpar can be used for testing kdump and fadump on LPARs
Logs
=======
linux-i4kf:~ # PS1=\[console-expect\]#
echo $?e-expect]#uname -a
uname -a
Linux linux-i4kf 4.12.14-100-default #1 SMP Fri Jun 7 13:05:05 UTC 2019 (ddfc532) ppc64le ppc64le ppc64le GNU/Linux
[console-expect]#echo $?
0
echo $?e-expect]#cat /etc/os-release | grep SLES
cat /etc/os-release | grep SLES
NAME="SLES"
[console-expect]#echo $?
0
[console-expect]#sed -i 's/crashkernel=[0-9]\+M/crashkernel=2G-4G:512M,4G-64G:1024M,64G-128G:2048M,128G-:409echo $?tc/default/grub;
24M,64G-128G:2048M,128G-:4096M/' /etc/default/grub;2M,4G-64G:10 
[console-expect]#echo $?
0
echo $?e-expect]#grub2-mkconfig -o /boot/grub2/grub.cfg
grub2-mkconfig -o …
> Added dumprestart_lpar and restart_lpar

- testcases/FWTS.py
Fixes this backtrace:
File "/mnt/testcases/FWTS.py", line 76, in version_check
return (self.MAJOR == 17 and self.MINOR >= 1) or self.MAJOR > 17
TypeError: '>' not supported between instances of 'str' and 'int'
> fix FWTS test for Python3

- testcases/OpTestKdumpLparSmt.py
This test validates kdump on SLES and RHEL with different smt levels.
> Adding test to validate kdump on lpar.

- testcases/OpTestInbandIPMI.py
We can get skiboot ipmi errors, so we should look at all lines of
output, not just the first - otherwise we get:
Command 'ipmitool mc selftest' exited with '1'. Output ['[
257.072567273,7] IPMI: Got error response. cmd=0x0, netfn=0x2d,
rc=0xc1', '[  257.076973965,7] IPMI: Got error response. cmd=0x0,
netfn=0x2d, rc=0xc1', 'Selftest: not implemented']
> Fix OpTestInbandIPMI test_mc for debug skiboot

- common/OpTestBMC.py
- common/OpTestIPMI.py
- common/OpTestOpenBMC.py
- testcases/OpTestFlash.py
- testcases/testRestAPI.py
Add some logic to handle bmc image flash on field mode as well
as add some debug logging to aide in problem determination.
> OpTestFlash: Updates for latest openbmc

- common/OPexpect.py
Allow pexpect to handle all binary data.
[console-expect]#PATH=/usr/local/sbin:$PATH pflash -r /dev/stdout -P VERSION
PATH=/usr/local/sbin:$PATH pflash -r /dev/stdout -P VERSION
Reading to "/dev/stdout" from 0x03228000..0x0322a000 !
File "/home/debmc/test3/testcases/OpalUtils.py", line 218, in runTest
self.flash_read_part()
File "/home/debmc/test3/testcases/OpalUtils.py", line 162, in flash_read_part
res = self.c.run_command(cmd, timeout=120)
File "/home/debmc/test3/common/OpTestIPMI.py", line 340, in run_command
return self.util.run_command(self, command, timeout, retry)
File "/home/debmc/test3/common/OpTestUtil.py", line 1502, in run_command
output = self.try_command(term_obj, command, timeout)
File "/home/debmc/test3/common/OpTestUtil.py", line 1531, …
> OPexpect: Python3 allow binary output

- testcases/OpalGard.py
Properly use floor/integer division.
File "testcases/OpalGard.py", line 95, in runTest
offset = hex(int(data["offset"])/16)
TypeError: 'float' object cannot be interpreted as an integer
> OpalGard: Fix python3 float type error

- OpTestConfiguration.py
- common/OpTestIPMI.py
- common/SerialConsole.py
Some BMC implementations provide *very* unreliably Serial over LAN
support. A workaround can be to hook up the physical host serial
port and use it through a serial concentrator.
Thus, this patch adds support to supply a command to run in order to get
access to that serial port. e.g. it could be "sshpass -p foo ssh
user:port@serial-concentrator" or something.
> Support Host Serial Console rather than IPMI SoL

- testcases/OpTestMtdPnorDriver.py
Regression introduced with d34b538ac3a38d68b5386219c0f0267344e6d37f
Changing arguments BMC_CONST.SCP_TO_LOCAL did not properly use the new correct method.
> OpTestMtdPnorDriver: Fix regression on copyFilesFromDest

- testcases/PciSlotLocCodes.py
Depending upon the version of lspci the output differs so ignore key errors.
> PciSlotLocCodes: Changes in lspci version

- common/OpTestASM.py
- common/OpTestTConnection.py
Apparently urllib in Python 2 didn't care about bad SSL certificates -
since op-test is typically used on development machines, we can
explicitly ignore HTTPS errors without worries, so do that.
The telnet code was broken since the Python 3 conversion, which shows it
doesn't get much mileage.  Handle all of the string/byte conversion
necessary, keeping with the idea that the telnet functions take a string
and return a string.
Signed-off-by: Russell Currey <ruscur@russell.cc>
> Python 3 fixes for ASM & telnet

- common/OpTestInstallUtil.py
Let's read vmlinux and initrd as binary to avoid
UnicodeDecodeError.
```
('# Webserver was asked for: ', '/vmlinuz')
----------------------------------------
Exception happened during processing of request from ('X.X.X.X', 49804)
File "/usr/lib64/python3.6/socketserver.py", line 639, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib64/python3.6/socketserver.py", line 361, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib64/python3.6/socketserver.py", line 696, in __init__
self.handle()
File "/usr/lib64/python3.6/http/server.py", line 418, in handle
self.handle_one_request()
File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
method()
File …
```
> Fixup: Python3: Read vmlinux and initrd as binary

- common/OpTestInstallUtil.py
Let's fix below errors by reading and writing with
proper decode/encode.
```
File "/home/bala/op-test-framework/common/OpTestInstallUtil.py", line 548, in do_GET
self.wfile.write(ps)
File "/usr/lib64/python3.6/socketserver.py", line 803, in write
self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
---
File "/home/bala/op-test-framework/common/OpTestInstallUtil.py", line 527, in do_GET
ps = d.format(REPO, PROXY, PASSWORD, DISK, DISK, DISK).encode()
AttributeError: 'bytes' object has no attribute 'format'
```
Reported-by: Balamuruhan S <bala24@linux.ibm.com>
Signed-off-by: Balamuruhan S <bala24@linux.ibm.com>
> Fixup python3: handle kickstart file read/write

- OpTestConfiguration.py
- common/OpTestOpenBMC.py
- common/OpTestSystem.py
- common/OpTestUtil.py
At conclusion of tests, gather the BMC logs for analysis.
> OpTestUtil: Add Gathering BMC logs

- common/Exceptions.py
- testcases/Console.py
Improve the Control-C/Z handling when connections lost.
This needs the latest Petitboot v1.10.x enabled ctrl-c.
> Console: Control-C/Z handling

- testcases/IplParams.py
Update risk level checks for native P9 Nimbus DD2.3
> IplParams: Add risk level checks for Native DD2.3

- doc/user-guide.rst
Add --host-pnor to Qemu example in documentation, clarifying that it
is needed for emulating the nvram
> Documentation: Add host_pnor to Qemu example

- testcases/IMC_bug.py
kernel OOPS is occuring when we try to cat files in IMC path.
Signed-off-by: Naveen kumar T <naveet89@in.ibm.com>
> IMC_bug.py:Adding test-case to find kernel_Oops in IMC path

- testcases/OpTestPrdDriver.py
`--pnor` option is not supported on FSP based system. And on
BMC based system `opal-prd` can detect right pnor.
Hence remove --pnor option.
> OpTestPrdDriver: Remove explicit passing of --pnor option

- OpTestLogger.py
Result of the python3 conversion, sometimes special characters in
petitboot cause errors in the debug logging.
I don't actually know if this works, sending this PR to trigger the CI and see what happens
> log: Fix logger encoding issues

- common/OpTestUtil.py
Set a short timeout for the logout on the bmc web server
in case things are hanging.
> OpTestUtil: bmc web logout timeout

- common/OpTestHost.py
Added function (host_is_kdump_enabled) to check if kdump is enabled or not.
Also added a check to find if start/stop of kdump was success, exit if it is
failed.
Added option --no-pager to systemctl status command, without this option the
command will wait to timeout because it expects "q" to quit.
Signed-off-by: Hariharan T S <hari@linux.vnet.ibm.com>
> Add support to check if kdump status and check for failure

- common/OpTestThread.py
The error message is as follows.
File "/home/ooo/Pnor_test/op-test/common/OpTestThread.py", line 122,
in inband_child_thread if time.time() > execution_time:
TypeError: '>' not supported between instances of 'float' and 'tuple'
Signed-off-by: Alvin Wang <alvinwang@msn.com>
> OpTestThread: Fix some errors

- common/OpTestSystem.py
Need to encode the string for socket.
> OpTestSystem: python3 encode sock.send

- common/OpTestFSP.py
- testcases/OpTestFlash.py
I've noticed my CI jobs occasionally get stuck in wait_for_standby()
when powering the system off before flashing skiboot
(OpTestFlash.FlashOpalLids):
Running tests...
----------------------------------------------------------------------
runTest (testcases.OpTestFlash.FSPFWImageFLASH) ... skip (0.016s)
runTest (testcases.OpTestFlash.BmcImageFlash) ... skip (0.009s)
runTest (testcases.OpTestFlash.PNORFLASH) ... skip (0.009s)
progress code [''], system state: runtime
progress code C100C1B0, system state: powering off
progress code C100C1B4, system state: powering off
progress code C1922000, system state: powering off
progress code C1922000, system state: powering off
progress code C1922000, system state: powering off
progress code C1922000, system state: powering off
progress code …
> FSP: avoid getting stuck in wait_for_standy()

- common/OpTestUtil.py
When parsing the op-test configuration from a hostlocker machine blurb
we take a slice of all the lines following the '[op-test]' section
header and currently we drop the last line by accident.
The stop value in Python's slice notation isn't inclusive, so the slice
lines[offset:-1] won't include the last element in the list (at index -1).
I am really good at python.
Signed-off-by: Oliver O'Halloran <oohall@gmail.com>
> Fix hostlocker parsing off-by-one

- common/OpTestHMC.py
Fix
1. timeout_factor None to 1 by default
2. wrong use of self in run_command_ignore_fail method
Signed-off-by: Harish <harish@linux.ibm.com>
> Fix: run_command_ignore_fail for HMC

- common/OpTestHMC.py
LPAR boot complete is determined by a combination of state and
refcode. So enhanced that in get_lpar_state()
Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>
> Handling LPAR boot completion on reboot

- testcases/OpTestCAPI.py
> OpTestCAPI: run memcpy afu CxlResetTest 10 times (instead of once)

- common/OpTestUtil.py
OpTestHost fails to get an ssh connection owing to expect tags which does not match SuSE prompt.
```
ConsoleSettings: Setting the prompt or logging in for the console was not successful, check credentials and review the following for more details
Expect Before Buffer="command-line line 0: Unsupported option "afstokenpassing"
Last login: Mon Apr 29 01:25:15 2019 from 9.124.35.213
linux-he6x:~ #
linux-he6x:~ # "
Expect After Buffer="<class 'pexpect.exceptions.EOF'>"
Message="Getting login and sudo not successful, probably connection issue, retry"
```
This patches fixes the above issue by adding a unique prompt
specific to handle SuSE prompt.
> Add ssh support for SuSE prompt

- common/OpTestOpenBMC.py
Swift systems are taking more than 10 minutes between poweroff/poweron.
Increase the timeout to 15 minutes.
> OpTestOpenBMC.py: increase wait_bmc() timeout

- common/OpTestOpenBMC.py
Reverts open-power/op-test#588
Apologies for the noise. I'm convinced that the root-cause for recent failures in the CI systems is not related to the timeout, so I'm reverting this.
> Revert "OpTestOpenBMC.py: increase wait_bmc() timeout"

- common/OpTestOpenBMC.py
- common/OpTestSystem.py
- testcases/OpTestHostboot.py
In early OpenBMC targets, we were told to issue both immediate (chassis)
as well as soft (host) poweroff in our sys_power_off() path. This is no
longer the recommendation, so adjust to be consistent with IPMI and LPAR
methods that issue an immediate power off.
Additionally, we're also been told that 30 seconds might not be enough
even for an immediate PowerOff in some (upcoming?) systems, so adjust
the SniffTest logic so we wait_for_standby() before issuing a PowerOn.
This should fix some CI scenarios where the BMC was executing a soft
power off (even if we're issuing both immediate and soft) and the 30
second delay was not sufficient before we could issue a poweron -
intermintently failing the test.
> Adjust OpenBMC PowerOff and global SniffTest

- testcases/OpTestInbandIPMI.py
Recent OpenBMC versions are now implementing the 'restart_cause' IPMI
command, but unsurprisingly the d-bus interface is not yet implemented,
so add this quirk to skip the test when getting an "Unspecified Error"
Additionally, allow this output to be in any of the command output's
list, because some IPMI daemon console errors might leak into this
command's output as well.
> Allow Unspecificed Error in SkirootFullInbandIPMI.test_chassis

- testcases/OpTestInbandIPMI.py
Recent OpenBMC versions are expected to answer with "Platform Event
Message command failed: Request data length invalid" for synthetic
ipmi events (used for testing cutting log records).
> InbandIPMI: Skip Synthetic event tests if unsupported

- testcases/Console.py
Due to an OpenBMC Bug we're intermittently hitting a timeout on
ControlC/ControlZ Console tests. Work around this by doubling the
timeout. On my tests, each iteration takes between 60-140 seconds, so
the 5 iterations are taking a good 10 minutes to complete, also
generating *a lot* of debug logs.
But before the OpenBMC bug is fixes, it's better than failing and
re-trying the test.
Once this is fixed, we should put this back to a sane default (say 10
seconds?)
> testcases.Console.Control[C|Z]: Increase timeout

- testcases/OpTestFastReboot.py
Skiboot 6.6 release notes has the following to say:
---
- Fast-reboot is now disabled by default.
Fast-reboot will continue to be supported, but as an opt-in feature rather
than the default. From the commit (ee07f2c68160) message::
This has two user visible changes:
1. Full reboot is now the default. In order to get fast-reboot as the
default the nvram option needs to be set:
nvram -p ibm,skiboot --update-config fast-reset=1
2. The nvram option to force a fast-reboot even when some part of
skiboot has called disable_fast_reboot() has changed from
'fast-reset=im-feeling-lucky' to 'force-fast-reset=1' because
it's impossible to actually use that 'feature' if fast-reboot is
off by default.
nvram -p ibm,skiboot --update-config force-fast-reset=1
---
Since we're expecting this testcase to …
> OpTestFastReboot: Add 'force-fast-reset' to nvram

- testcases/OpTestFastReboot.py
.. so that we are sure that the reboot command arrives before our
attempt to grep the log for the fast reset message..
> OpTestReboot: add half-second delay to reboot

- op-test
Something in between skiboot-v6.6-85-gabe4c4799 and
skiboot-v6.6-111-gd362ae4f4 broke fast-reset.
Disabling temporarily while we figure it out.
> SkirootSuite: Temporarily Disable FastReboot

- op-test
Reverts open-power/op-test#605
https://github.com/open-power/skiboot/issues/259#issuecomment-735674424 got fixed.
> Revert "SkirootSuite: Temporarily Disable FastReboot"

- OpTestConfiguration.py
- common/OpTestFSP.py
Currently, when logging into FSP op-test expects the machine to have the prompt
"$". When a machine has a different prompt (my machine has "fspbash-4.2#"), the
test gets stuck expecting "$" and doesn't move on.
This patch adds the ability to send in a custom FSP prompt as an argument.
Signed-off-by: Cristobal Forno <cforno12@linux.ibm.com>
> OpTestFSP: pass in custom fps prompt to constructor

- ci/build-qemu-powernv.sh
Fixed qemu version in CI code, so that travis check can pass.
> Fix qemu version in ci

- OpTestConfiguration.py
- common/OpTestHMC.py
- testcases/OpTestLPM.py
Enable LPM tests. This patch will enable migration with in
same HMC and different managed system.
1. Framework enablement for lpar migration
2. Simple test to migrate from source to destination
> Enable LPM test

- testcases/InstallUpstreamKernel.py
Parse the initrd file name correctly for kexec to use the proper
initrd file, in a case where we have 2 initrd file with same kernel
release version, the existing script choses the last file, this code
will make sure it uses the exact initrd file for kexec
> InstallUpstreamKernel.py: fix initrd file string

- common/OpTestUtil.py
Sometimes the login prompt takes more time to login and the times out
before expecting last login: prompt, so increased the timeout
> OpTestUtil.py: Increase login expect timeout

- testcases/InstallUpstreamKernel.py
the rm command takes more time if the linux source file is too big
and timesout with default 60s, so added timeout with increase time
> InstallUpstreamKernel.py: add timeout value

- common/OpTestHMC.py
In case of slow network connectivity the response to console
commands are little late, so increasing wait between the console
commands will solve multiple timing issues
> Increase stall time by 2 secs

- testcases/InstallUpstreamKernel.py
commit 22ce7b0e8e0d InstallUpstreamKernel.py: add timeout value 
introduced a timeout value to fix a problem while removing large source
files. Unfortunately it introduced following error due to extra paranthesis
File "./op-test", line 37, in <module>
from testcases import InstallUpstreamKernel
File "/home/jenkins/workspace/UpLiKeROPO/testcases/InstallUpstreamKernel.py", line 93
(linux_path, linux_path), timeout=120))
^
SyntaxError: invalid syntax
This patch fixes the issue.
> InstallUpstreamKernel - Fix syntax error 

- OpTestConfiguration.py
- common/OpTestInstallUtil.py
- testcases/OpTestKernelArg.py
1. Fix: Extract commandline arguments properly
awk fails to get the proper kernel commandline params as few of the contain "=" character. Hence using a more easier way to get the entire string.
Using str.replace instead of strip which only string leading or trailing matches.
Also define output variable before use
2. Add distro parameter to update grub
Patch adds distro level so that grub configuration can be updated according to the same
3. Add --use-reboot command line option for OpTestKernelArg test
Patch adds --use-reboot command line option to explicitly use reboot command once kernel command line is updated
Signed-off-by: Harish <harish@linux.ibm.com>
> Fixup and few enhancements for kernel command line test

- common/OpTestASM.py
- common/OpTestHMC.py
- testcases/OpTestHugepage.py
Patch adds test to configure and validate 16G hugepages. The following steps are performed sequentially for validation.
1) Get the configured hugepages from LPAR profile
2) Update the LPAR grub with hugepage kernel commandline
parameters
3) Power off the LPAR and managed system
4) Configure sample hugepages through ASM
5) Power on the managed system
6) Update the LPAR profile with incremented hugepages
7) Power on the LPAR with the profile
8) Verify if 16G hugepages are configured properly at OS level
9) Revert LPAR profile config and kernel parameters
Signed-off-by: Harish <harish@linux.ibm.com>
> Add test to validate 16G hugepage

- common/OpTestHMC.py
On some HMC controlled systems, InstallUpstreamKernel testcase gets stuck
at get_console() just after executing kexec -l command.
xxxxxx login:
Red Hat Enterprise Linux 8.4 (Ootpa)
Kernel 4.18.0-305.el8.ppc64le on an ppc64le
Activate the web console with: systemctl enable --now cockpit.socket
xxxxxxx login:
The timeout value of 10 seconds in pty.expect() comand for "login:" is not sufficient.
Increase the timeout to 60.
> InstallUpstreamKernel: Increase timeout value in pty.expect() comand for "login:"

- OpTestConfiguration.py
Have used these parameters in dump over ssh and nfs in PowerNVDump.py.
Changed --server-ip to --dump-server-ip and --server-pw to --dump-server-pw as suggested in previous PR.
> Added config parameters for dump over network - v4

- OpTestConfiguration.py
- common/OpTestHMC.py
- op-test
- testcases/OpTestDlparIO.py
The patch will enable dlpar tests on PowerVM boxes
1. Add, Remove and move the PCI and SRIOV cards
> Enable Dlpar tests on PHYP systems

- common/OpTestHMC.py
- testcases/OpTestLPM.py
The following issues are addressed
1. Overide default timeout to that of ideal value for migration
2. Check for required packages installed for migration
3. Disable firewall before starting the migration.
Using teardown function to enable firewall.
4. Start the rsct services before migration.:
> Prerequisites check for LPM test and added timeout for migration

- op-test
Suite contains all the kdump test that is triggered on linux kernel
like local, ssh, nfs etc
> Create a OS kdump suite to cover linux crash dumps

- common/OpTestHMC.py
wait_[lpar|system]_state function checks for expected state for an LPAR/System
after a poweron/poweroff (and other similar) operation. These functions have
an exit condition(count variable) for cases where change of state for
LPAR/system fails after certain number of retries.
Unfortunately the counter never gets incremented which results in infinite loop.
> common/OpTestHMC: Rectify exit condition logic for wait lpar/system state

- common/OpTestHMC.py
- testcases/OpTestLPM.py
Basic LPM will run even if user does not specify VIOS parameters (lpar_vios, remote_lpar_vios) in config file.
Logs:
[test-log-with-vios.log](https://github.com/open-power/op-test/files/7947997/test-log-with-vios.log)
[test-log-without-vios.log](https://github.com/open-power/op-test/files/7947998/test-log-without-vios.log)
> Modified LPM to work with/without VIOS parameters being specified

- common/OpTestUtil.py
- testcases/OpTestDlparIO.py
Add new function "check_pci_type"  to OpTestUtil.py  to determine whether the given pci_device is of type ethernet or FC .
> Check DLPAR pci_id is of ethernet type or fc type

- testcases/InstallUpstreamKernel.py
InstallUpstreamKernel testcase relies on grubby command to update boot
loader configuration. On hosts running certain Linux flavours which does
not support this command the test fails with command not found error:
[console-expect]#grubby --set-default /boot/vmlinuz-`cat include/config/kernel.release 2> /dev/null`
grubby --set-default /boot/vmlinuz-`cat include/config/kernel.release 2> /dev/null`
bash: grubby: command not found
Use grub2-set-default command to specify the boot order. Also switch the
order of grub2-mkconfig and grub2-set-default commands to ensure that all
installed kernels are accounted for before choosing the default one.
> testcases/InstallUpstreamKernel: Use grub2-set-default inplace of grubby

- testcases/InstallUpstreamKernel.py
testcases/InstallUpstreamKernel: Replace remaining instances of grubby
commit 258fb8545f1f switched from grubby to grub2-set-default command.
This change was done only for non kexec use case. Switch to using the same
command for use_kexec case as well.
testcases/InstallUpstreamKernel: Perform a clean kexec reboot
kexec -l / kexec -e sequence is prone to failures since it does not go through
a clean shutdown/reboot. The recommended way is to either use kexec
without -l option avoiding use of another follow-up kexec command or use
kexec -l with reboot. Both these methods ensures a clean boot on kexec.
> testcases/InstallUpstreamKernel: grub and kexec handling fixes

- testcases/InstallUpstreamKernel.py
As Now issue like in config need to placed in test_binaries as this is hardcoed path , this patch address
that config can be placed any where inside op-test working directory
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>
> This Patch address issue when user provide local config to kernel build

- testcases/OpTestDlpar.py
Testcase is failing with error "'random' is not defined", fixed this error.
> Fixed "'random' is not defined" error.

- common/OpTestHMC.py
- common/OpTestVIOS.py
Logs a warning to collect the snap logs (which has been renamed) and
the pedbg logs.
> Logs warnings to collect pedbg and snap logs manually

- testcases/PowerNVDump.py
Takes care of configuration of IP, and performs kdump over private IP (both SSH and NFS).
> Added provision for Kdump (NFS and SSH) over Private IP

- common/OpTestVIOS.py
- doc/programming.rst
Add VIOS package to the doc
common/OpTestVIOS.py: add doc string data to functions
doc/programming.rst: add VIOS package information
Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>
> Add VIOS package to doc

- common/OpTestHMC.py
- testcases/OpTestLPM.py
- To perform inactive LPM, a boolean value can be provided in the
config file using parameter "inactive_lpm"
- System powered off before migration, and powered on upon completion
of migration.
- No OS logs are collected and no dmesg error checking is performed
if inactive LPM is performed.
> Added provision for inactive LPM

- op-test
- testcases/OpTestLPM.py
Based on user input i.e target_hmc_ip in conf, suite
decide whether to run local hmc or remote hmc test
Also removed the suite from inside the test
> Update lpm-suite to run single or remote hmc test

- op-test
Make sure kdump over disk is run only if dev_path is given
do not fail network dump if dev_path is not given
> Update osdump-suite to run as per user input

- common/OpTestUtil.py
If the log file is not present, no error is thrown.
> Error handling if OS file log not present

- common/OpTestSystem.py
OpTestLPARSystem iniitalization includes a call to fsp_get_console. This function call disables firewall, opens a connection to FSP and records its hostname. This call isn't necessary for LPAR based system and possibly was inherited from OpTestFSPSystem class.
Don't call this function so that it does not alter the FSP configuration(iptable rules).
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>
> op-test/common: Skip fsp_get_console call

- testcases/PowerNVDump.py
This test covers below scenarios:
1. kdump/fadump after cpu add.
2. kdump/fadump after cpu remove.
3. kdump/fadump after memory add.
4. kdump/fadump after memory remove.
> Added testcase for kdump/fadump after dlpar - v2

- testcases/PowerNVDump.py
Default crashkernel value might not be suffcient for kdump sometimes, so changing crashkernel value based on memory. Also deleting the line changing the path variable as we are restoring original the kdump.conf after each test.
> Added code to configure crashernel value - v4

- testcases/OpTestEnergyd.py
This test covers below scenarios:
Starts energyd service and checks if it is active. Verifies if the number of online cores reduces to 2 when service is active in powersave mode. This test verifies that all cores are online in max performance mode even if service is active. This test verifies that all cores come online when workload is started even in powersave mode.
> Test to verify energyd service functionality - v2

- testcases/OpTestLparFreq.py
This test covers below scenarios:
Set Powersave mode to different available modes and check whether the mode is changed accordingly in OS. Set Powersave mode to different available modes and check whether the frequency chages accordingly. Check frequency is lowest in "powersave" mode and maximum in "Maximum Performance Mode" Set Powersave mode to "Staic Power Saver" mode when lpar is deactivated and check if the mode is set properly when the lpar boots up. Sets Powersave mode to different powersave modes and checks frequency with and without workload. Sets Powersave mode to different powersave modes and verifies frequency with different smt modes.
> Test to verify lpar frequency with different powersave modes - v4

- testcases/OpTestLPM.py
stress-ng package is must for LPM with stress-ng
load, and test fails if package is not installed
> Added stress-ng package check

- testcases/PowerNVDump.py
On slow lpars network tests are failing due to scp timeout and sshpass install timeout so increasing the timeout value.
> Fixed testcase failure due to timeouts.

- testcases/PowerNVDump.py
The current test fails for EBMC_PHYP lpars,
so added a check along with FSP_PHYP to support
eBMC lpars
> kdump: add support for ebmc_phyp lpars

- testcases/PowerNVDump.py
Fadump by default uses cma, this test verifies fadump without cma.
> Test to verify fadump with nocma.

- common/OpTestHMC.py
While working with multiple reboot tests, the test requires to login and set unique prompt multiple times, so currently the raw pty console get_console is designed to work for one time login, so when OS reboot happens in mid of test, this requires to reset prompt, sudo, login parameters, setup_term can reset the prompt post login and continue test flow
> Reset unique prompt for multi reboot usecases

- common/OpTestHMC.py
Changed the existing command of chsyscfg which is going to set the lpar profile as expected
> OpTestHMC.py : Lpar configuration command is not working as expected

- testcases/InstallUpstreamKernel.py
Removing old linux source some time takes more than 2 mins so increase timeout from 120 to 600
> linux install: Increase command timeout to delete source

- testcases/InstallUpstreamKernel.py
In previous commit we are using regex module in the code but we missed importing it
> upstreaminstall: add missing re module import

- OpTestConfiguration.py
- common/OpTestHMC.py
- testcases/MachineConfig.py
This test helps to change lpar profile to shared mode, dedicated mode, enable vtpm and configure pmem. Also to configure LMB to 256mb,1gb,2gb,4gb
> Testcase to change the lpar configuration - v4

- testcases/OpTestLPM.py
There are some more expected dmesg error messages, for which LPM test fails, but they are expected, so added them into skip errors
> LPM: Add expected error messages while LPM

- testcases/Lcov.py
This code will copy back the html result file to the source path from where we have triggered the test case.
> Enhancing the Lcov.py to copy back the html files of test results

- common/OpTestUtil.py
get_distro_details() : This API reads the entire /etc/os-release file, and formulates the details into a dictionary format which, in-turn, can further be used to fetch other relevant details by adding a wrapper function above this API just like the way get_distro_version() retrurns the version.
get_distro_version() : Reads the version information from the metadata returned by get_distro_details() and returns the distro version for a specific distro.
> OpTestUtil : Added functionality to fetch distro version

- testcases/OpTestKexec.py
As secure boot os utils are moved from OpTestHMC to OpTestUtils so reflecting the same in the OpTestKexec testcase
testcases/OpTestKexec.py", line 44, in <module>
from common.OpTestHMC import OpSecureBootUtilities ImportError: cannot import name 'OpSecureBootUtilities'
> Fix: OptestKexec import errors due to utils change

- common/OpTestHMC.py
- testcases/MachineConfig.py
Added logic to add/remove physical IO adapter to lpar profile
OpTestHMC.py is updated with definition to add/remove adapter MachineConfig.py is updated to call definitions defined in common
> Implemented logic to add/remove physical IO adapter to lpar profile

- common/OpTestHMC.py
- common/OpTestUtil.py
- testcases/MachineConfig.py
- Implemented config based APIs to enable / disable secureboot at the lpar-level & the os-level.
- Also added some related functions to cater the needs of the above two main APIs : os_secureboot_enable() hmc_secureboot_on_off() getPRePDisk() backup_restore_PRepDisk() check_secureboot_state()
> MachineConfig.py : Secureboot config based APIs

- testcases/PowerNVDump.py
Existing check for vmcore file was done based on wildcard search on string pattern vmcore*. In case of failure,  kdump creates "vmcore-dmesg-incomplete.txt" file in crash directory. In case of failure, that logic wrongly picks this file as vmcore file and tests pass though vmcore not generated. This fix checks  "vmcore-dmesg-incomplete.txt" file. If that file exists, then testcase fails with OpTestError. Otherwise , in successful case , there is check for  vmcore file, that should be one of these formats (vmcore, vmcore.flat, vmcore.1, vmcore.2 ....etc). If the vmcore file doesn't exist , then testcase fails with OpTestError.
The  vmcore file is saved under /var/crash/ip-date/vmcore
CASE 1 : when vmcore dump collection was successful  , file name formats could be shown as below …
> Fix false positives with op-test kdump testcase

- op-test
- testcases/OpTestKexec.py
There are three patches to improve kexec tests 
OpTestKexec: add test suite for kexec
OpTestKexec: revamp kexec test cases
OpTestKexec: simplify setUp function
And a patch that fixes and issue with --list-suite option
op-test: Align doc string for system access suite
> revamp kexec test and a fix for op-test --list-suite option

- testcases/GcovSetup.py
- testcases/Lcov.py
Moved testcase logic to use generic kernel path which can help user to not have diffrent path
> Moved testcase logic to use generic kernel path

- OpTestConfiguration.py
- common/OpTestEBMC.py
The previous patch restricted user to set system as phyp only, blocking it to run any bmc commands. so this fixes allowing to instantiate both phyp and bmc objects, and set system type based on the user config parameter given
> EBMC: Allow user to run bmc commands over ssh

- common/OpTestHMC.py
- testcases/MachineConfig.py
In case of any LAPR key does not have value op-test error out as
ERROR: runTest (testcases.HelloWorld.HelloWorld)
---------------------------------------------------------------------- Traceback (most recent call last):
File "/home/op-test/testcases/HelloWorld.py", line 44, in runTest
exist_cfg = self.cv_HMC.get_lpar_cfg()
File "/home/op-test/common/OpTestHMC.py", line 309, in get_lpar_cfg
value = data[1]
IndexError: list index out of range
as this fix populate that value as null string
> Fix IndexError: list index out of range issue

- testcases/InstallUpstreamKernel.py
The patch fixes the timing issue due to which compiled upstream kernel was not booting on to the LPAR.
> Adding Time Delay after Upstream kernel compilation before reboot starts.

- op-test
- testcases/PowerNVDump.py
1. Checking for fadump=on in kernel parameter argument list.
If it exists , then remove fadump=on before the execution of
kdump testcases.
2. Addressed console issue not returning to command prompt
for "echo 1 > /sys/kernel/fadump_registered"
3. Cleanup for hugepage config on hugepage size 1GB
> Remove Fadump=on before kdump testing

- testcases/PowerNVDump.py
After we modify ( i.e  add/remove)  list of   kernel arguments , we need to  run the following commands to make sure that console is properly available for the next testcase to be executed.
self.cv_SYSTEM.goto_state(OpSystemState.OFF)
self.cv_SYSTEM.goto_state(OpSystemState.OS)
Earlier , kdump testsuit execution flow  was interrupted in-between  with this kind of error message:
op-test.common.OpTestUtil:try_sendcontrol:WARNING:OpTestSystem detected something, working on recovery
op-test.common.OpTestUtil:try_recover:WARNING:OpTestSystem detected something, working on recovery
op-test.common.OpTestHMC:connect:INFO:De-activating the console
op-test.common.OpTestHMC:connect:INFO:Opening the LPAR console
op-test.common.OpTestUtil:try_recover:WARNING:OpTestSystem recovered from temporary …
> Fix console timeout issue in kdump/fadump tests

- OpTestConfiguration.py
- op-test
- testcases/BisectKernel.py
This commit introduces support for automated git bisect in the op-test framework. This test  aims to streamline the process of identifying and isolating issues using the git bisect functionality within the op-test
environment.
**Steps to Bisect Kernel**
**Build Issue**
**Configuration**
```
[op-test]
bmc_type=OpenBMC
bmc_ip=bmc_ip
bmc_username=root
bmc_password=password
host_ip=host_ip
host_user=root
host_password=password
host_cmd_timeout=36000
git_repo=git@github.com:AboorvaDevarajan/linux.git
git_repo_reference=/home/ci/linux-ref
git_branch=bisect_build_fail
good_commit=69baa3a623fd2e58624f24f2f23d46f87b817c93
bad_commit=2db88d600dc4ca38a5542f4e2bee1c3549c34b83
bisect_script=
bisect_category=BUILD
```
**Bisect Command**
```
./op-test -c machine.conf --run testcases.BisectKernel
``` …
> bisect: add support for automated git bisect in op-test

- testcases/OpTestLPM.py
checking the error levels up to level 4 for LPM tests than the default level 5 1 - emerg
2 - emerg,alert
3 - emerg,alert,crit
4 - emerg,alert,crit,err
5 - emerg,alert,crit,err,warn
> dmesg error level check for lpm test

- testcases/Lcov.py
we have some issue with Lcov tool due to which coverage is exiting with error. added some work around for time being by just ignoring the produced errors.
> Tinkering Lcov.py to ignore lcov tool errors

- common/OpTestHMC.py
Added two functions which is going to return the CPU and memory available on the CEC.
> common/OpTestHMC.py: Added code to get available resources from CEC

- testcases/MachineConfig.py
Added support which boots the lpar into dedicated mode by setting the max procs to the available procs of CEC
> MachineConfig.py: Add support for max procs to available procs of CEC

- OpTestConfiguration.py
- README.md
This PR contains two minor changes:
1. feat: allow op-test usage from anywhere
Currently, if a symlink to 'op-test' is created somewhere (such as in
/usr/local/bin/), it fails to start with following error:
```
$ cd /usr/local/bin
$ ln -sv PATH_TO_op-test/op-test
$
$ op-test --help
File "/tmp/./op-test2", line 125, in <module>
OpTestConfiguration.conf = OpTestConfiguration.OpTestConfiguration()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/op-test/OpTestConfiguration.py", line 492, in __init__
for dirname in (next(os.walk(os.path.join(self.basedir, 'addons')))[1]):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```
This is because, `self.basedir` is pointing to the current working
directory or path of the symlink (sys.argv[0]), …
> Enable op-test to be used from anywhere

- common/OpTestHMC.py
- testcases/MachineConfig.py
1.Added support which boots the lpar into dedicated mode by setting the max memory to the available memory of CEC. 2.common/OpTestHMC.py:Added memory part to change_proc_mode function
> MachineConfig.py:Add support for max memory to available memory of CEC

- common/OpTestHost.py
- testcases/PowerNVDump.py
This test verifies "watchdog module" with different scenarios like
1. Watchdog module load and unload.
2. watchdog with action 1/ Reboot LPAR.
3. watchdog with action 0/ Halt LPAR.
4. watchdog with action 2 /dump collect
a. dump collect to a local disk
b. dump collect to a NFS disk
c. dump collect to a SAN FC disk
> "watchdog Kernel module" functionality with diffrent supported parameters.

- testcases/PowerNVDump.py
Fadump  tests in op-test framework  frequently timed-out due to console issue , after  we run the command "echo 1 (or 0) >/sys/kernel/fadump_registered" from console. This was needed for op-test framework where we run commands on remote machine. After the execution of this command , it does not return the prompt( Instead it hangs/time out) . It needs another manual enter key to get console prompt. So , fix was to send newline after setting fadump_registered
> Fix console hang issue after setting fadump_registered value

- common/OpTestHMC.py
- testcases/MachineConfig.py
1.Added support which boots the lpar into shared mode by setting the max virtual procs to 3 times of max PU .
> MachineConfig.py:Add support which boots the lpar in user defined shared mode

- testcases/PowerNVDump.py
To avoid static values and manual updates to crashkernel size, ServiceReport was added to auto correct crashkernel size before running the kdump/fadump testcases
> Add ServiceReport to RHEL distro on kdump/fadump tests

- op-test
The existing `OSdumpSuite()`  can be split into two separate test suites for kdump and fadump for following reasons :
1) When there was failure in kdump testcase , it blocked fadump tests completely. This way, fadump test execution will not be interrupted by kdump test failure.
2) There was mix of local and remote dump collection test cases between test flow. So , with this change , execute all local dump related tests together (at the beginning) . Later run the remote dump target tests . This will avoid extra effort in fixing the test configuration (/etc/kdump.conf  or /etc/sysconfig/kdump)  changes,  when switching from local to remote dump targets (vice-versa )
> Split kdump and fadump test suites to run separately

- op-test
- testcases/OpTestHtxBootme.py
The test is performed in below manner
1. Starts Htx workload on mdt.all
2. Starts bootme which reboots the lpar every 30 minutes
3. wait for reboot and check htxerror logs after reboot, Htx must continue without any errors
4. Stop bootme
5. Stop Htx workload
Param : "boot_count" must be given from machine.conf file. The param is for the number of counts the reboot cycle must happen. Default is 6
```
machine.conf
[op-test]
bmc_type=
bmc_ip=
bmc_username=
bmc_password=
host_ip=
host_user=
host_password=
hmc_ip=
hmc_username=
hmc_password=
system_name=
lpar_name=
time_limit=
time_unit=
boot_count=
mdt_file=
htx_rpm_link=
```
> Adding HtxBootme test on OpTest

- testcases/OpTestHtxBootme.py
There were 2 indentation issues caused during the First PR shared on Htxbootme Optest. Fixing those errors.
> Fixing indentation error in htxbootme test code.

- testcases/OpTestKexec.py
Add new test cases with -s and -c options.
test case with -c option should fail when secure boot is enabled
> testcases/OpTestKexec.py: add new test cases with -s and -c options

- op-test
- testcases/PowerNVDump.py
ServiceReport fails to estimate correct crashkernel size. This is a temporary fix to define crashkernel size
> Fix kdump/Fadump config

- testcases/PowerNVDump.py
Properly handle cleanup of left over kernel arguments  in case of failure from hugepage_checks() , KernelCrash_XIVE_off()  and KernelCrash_disable_radix()
> Fix removal of kernel args left from previous testcase

- testcases/PowerNVDump.py
The vmcore saved in makedumpfile flattened format bydefault on SLES. Inorder to test makedumpfile options like --split..etc, that flattened format should be converted into kdump-compress format.
> Convert vmcore file format to kdump-compress format on SLES

- testcases/PowerNVDump.py
There was a failure due to timeout during backup copy of kdump config file in SLES .This PR adds timeout similar to RHEL case.
> kdump verify dump needs timeout for copying kdump config file on SLES

- testcases/OpTestHtxBootme.py
This ssh connection to host is used to get directory paths, htxerr files and many other validations.
> Replacing Paramiko with ssh connection to host

- testcases/PowerNVDump.py
Failures observed when getting the ebizzy package incase that  package was already existing . Also , added timeouts for tar package, configure , make steps because sometimes it may take longer time to finish the task  due to network delays
> The ebizzy testcase of kdump needs cleanup and timeout set

- testcases/PowerNVDump.py
The kernel commit d418b19f34ed ("powerpc/fadump: Reorganize
/sys/kernel/fadump_* sysfs files") has relocated all fadump sysfs
entries from /sys/kernel/fadump_* to a new place /sys/kernel/fadump/*.
Therefore, let's utilize the updated sysfs entries to prevent the fadump
test from breaking in case the kernel removes the old entries in the
future.
Note: the new fadump sysfs entries have been present since kernel
version 5.6-rc2, so this change should not cause any issues during
fadump testing on all the latest distributions.
> testcases/PowerNVDump: use updated fadump sysfs files

- testcases/MachineConfig.py
This enhancement introduces support for configuring multiple lpars, such as lpar1, lpar2, and so on, especially when they are in shared mode.
To configure the multiple lpars user need to pass below two parameters, lpar_config=multi lpar_list=lpar1, lpar2 ...etc
In this case, users are required to explicitly specify these two parameters in the .conf file, and it's important to ensure that all lpars have unique passwords.
> Added support to configure the multiple lpars-v5

- testcases/InstallUpstreamKernel.py
Sometimes the console via ssh is not connected and Login attempt fails, This could be due to network issue. Attempting to login for 5 times if the connection is not established in one go.
> Patch helps to overcome login issue.

- testcases/InstallUpstreamKernel.py
With latest grub2 installer, one should set the
kernel to be booted explicitly after update or
install of latest kernel
> Add grubby to handle latest grub2 changes

- common/OpTestHMC.py
- testcases/MachineConfig.py
CPU:Added support to get the procs assigned to not activated lpars and adding them to the max_procs of the target lpar along with the proc available from the CEC
Memory:Added support to get the memory assigned to not activated lpars and adding them to the max_memory of the target lpar along with memory available from the CEC
> Added support to get stealable resources from Not Activated lpars

- testcases/PowerNVDump.py
In some scenarios, there were failures with error ""Test currently supported only on ubuntu, sles and rhel" . This was because of the "run_command" from console . That takes much time causing hang . It worked with "run_command" executed from host
> Testcase cleanup for timeout and hang

- common/OpTestUtil.py
- testcases/GcovSetup.py
1- [Fixed Support for Suse source package can be get via API]
2- [added support in get kernel source in suse case]
> Fix suse gcov

- common/OpTestHMC.py
- common/OpTestUtil.py
In some LPARS with some distros, the time it takes between user and password is more than 10 sec, so
increase the timeout
> Fix timing issue when login and passowrd

- common/OpTestHMC.py
- common/OpTestInstallUtil.py
- testcases/OpTestFastReboot.py
- testcases/OpTestHMIHandling.py
- testcases/OpalMsglog.py
Currently there are syntax warnings present in the code while running ./op-test test cases.
These syntax warnings are about using "==" and "!=" in place of "is" and "is not" respectively
This simple patch will eliminate the syntax warnings
Signed-off-by: Misbah Anjum N [misanjum@linux.vnet.ibm.com](mailto:misanjum@linux.vnet.ibm.com)
> Fix Syntax warnings on running ./op-test

- OpTestConfiguration.py
- common/OpTestUtil.py
- op-test
- test_binaries/make.sh
- testcases/OpTestKernelTest.py
This is a new testcase for kernel build with build bisection support having email support, storing the build status in json and proper error handling and also support for linux-next bisection and a flag to skip bisection
Libraries added for error message parsing, build bisection email format, get git details
Added make.sh for kernel build bisection
> OpTestKernelTest: Kernel build test with bisection

- testcases/MachineConfig.py
We need to boot the lpar in shared mode as per user requirement. so removed a check
> MachineConfig.py: Removed a condition which checks the lpar is in shared mode

- testcases/OpTestKernelTest.py
Addition of KernelBoot class in the testcase to
support kexec boot of Upstream Linux Kernel
> OpTestKernelTest: Kernel kexec boot

- common/OpTestUtil.py
With fedora OS, the ssh login prompt has more extra brakceted console characters so make sure to include as wildcard
prompt:
^[]0;root@ltclp2:~^G^[[32mroot@ltcrain4-lp2^[[0m:^[[32m~^[[0m#^[[0m
error:
self.connect(logger)
File "/data/jenkins/workspace/sandbox/install/op-test/common/OpTestSSH.py", line 185, in connect
self.check_set_term()
File "/data/jenkins/workspace/sandbox/install/op-test/common/OpTestSSH.py", line 200, in check_set_term
self.util.setup_term(self.system, self.pty,
File "/", line 1709, in setup_term
raise ConsoleSettings(before=pty.before, after=pty.after,
common.Exceptions.ConsoleSettings: Setting the prompt or logging in for the console was not successful, check credentials and review the following for more details Expect Before Buffer="command-line line 0: Unsupported …
> Fedora: handle ssh prompt with extra console chars

- common/OpTestUtil.py
- testcases/PowerNVDump.py
We have observed  tests timing out with console  Warning .  kdump/fadump Makedumpfile testcase failed with timeout in Power9 CR.  To overcome this issue , added timeout as per the requirement . 
```
ERROR: runTest (testcases.PowerNVDump.OpTestMakedump)
----------------------------------------------------------------------
File "/var/lib/jenkins/workspace/TestRunner@2/op-test/testcases/PowerNVDump.py", line 1311, in runTest
self.makedump_check()
File "/var/lib/jenkins/workspace/TestRunner@2/op-test/testcases/PowerNVDump.py", line 1267, in makedump_check
"The dumpfiles are saved to dump3, and dump4")
File "/var/lib/jenkins/workspace/TestRunner@2/op-test/testcases/PowerNVDump.py", line 1239, in check_run
res = self.c.run_command(cmd)
File …
```
> Add timeout value for console based run commands in kdump tests

- common/OpTestUtil.py
Sles uses the different package name for kernel src. earlier we used kernel-default. But the package names are like kernel-source. Again fot build it uses kernel-default only but for install it uses kernel-source. So just changing it to kernel-source.
> Changing the kernel package name for sles distro kernel_src build

- common/OpTestHMC.py
- testcases/MachineConfig.py
Fix EC Min/Desired Proc Units Calculation and Max Virtual Proc Units Logic
Previously, for EC, the `min_proc_units` were calculated by multiplying the user input with the `overcommit_ratio`. This caused an issue where users were unable to set their desired `min_proc_units` for EC. To fix this, the `overcommit_ratio` is no longer used in calculating `desired_proc_units`, as it should only be applied when determining the virtual proc units. The `desired_proc_units`, `max_proc_units` and `min_proc_units` are now set directly based on the user's inputs for EC.
Additionally, we added logic to calculate the max virtual proc units by fetching the maximum virtual procs configured in the system. We use this value as the max virtual proc count, but there is a condition where the available stealable …
> Fixed the issue for seating the shared mode  EC vs VP value.

- testcases/Lcov.py
we do not need tiny* for sles hence removing the same for sles and keeping the package for rhel
> Fixing the packaging issue in Lcov.py

- testcases/PowerNVDump.py
servicereport plugins  corrected to fadump  when the system under test was set to fadump mode .
```
servicereport 2.2.3
FADump configuration check                          PASS
Active dump                                       PASS
Dump component in initial ramdisk                 PASS
FADump enabled check                              PASS
FADump registration check                         PASS
Service status                                    PASS
kexec package                                     PASS
Memory reservation                                PASS
Package availability check                          PASS
ppc64-diag                                        PASS
irqbalance                                        PASS
perf                                              PASS
sos …
```
> Fix servicereport argument for fadump package repair

- testcases/PowerNVDump.py
The old url is not working and the test is hung, so the URL is now changed to working link
> fix ebizzy url link fail to wget

- common/OpTestHMC.py
- common/OpTestSSH.py
- common/OpTestUtil.py
- testcases/OpTestKernelTest.py
This code is modifed and develped on top of the previous code (2f103 : OpTestKernelTest: Git bisect automation..)
With version 2.0 these are the new changes added:
1. Added support to handle nested bisection loop, which was not working with previous code
2. Modified code to work for end to end CI server
3. Better handle all cases of good flow and bad flow
4. Add json store of good boot commit for good run
5. Fix the previous code blocker to properly manage the console thread
TODO:
Add boot json generation after bisection with bad commit
Email format for boot bug report
> OpTestKernelTest: Add support for automated boot bisection v2.0

- testcases/MachineConfig.py
For the below combination of MachineConfig the job fails {"lpar":"cpu=dedicated,vpmem=1,vtpm=1","os":"hugepage=2M"}
as the lparconfig power off and on the lpar and than the osconfig do not find the prompt ready to run os commands
so with this fix we are waiting for lpar os to boot till login and closing the console for next osConfig to open and reset the prompt and continue
> MachineConfig.py: osconfig command fails due to no prompt

- testcases/PowerNVDump.py
OpTestMakedump testcases in kdump/fadump testsuite  were failing due to timeout issue . 
some of the commands execution took approximately  2 minutes  as shown below:
[console-expect]#time makedumpfile -d 31 -p vmcore dump43
The kernel version is not supported.
The makedumpfile operation may be incomplete.
Copying data                                      : [100.0 %] \           eta: 0s
The dumpfile is saved to dump43.
makedumpfile Completed.
real    1m51.007s
user    1m45.221s
sys     0m5.769s
[console-expect]#
> Fix mkdumpfile timeout

- common/OpTestHMC.py
In the previously added code, it was observed that when the condition max_proc_units > max_virtual_proc is true, the system assigns the maximum virtual processors as returned by the LPAR configuration. However, an issue arises when the LPAR returns a maximum virtual processor count that is less than the max_proc_units. In such cases, the HMC fails to configure the EC vs VP values according to the virtual processors' thumb rule, which mandates that virtual processors should always be greater than or equal to EC processors.
This patch addresses and resolves the issue.
> Fixed EC vs VP setting for shared mode LPAR configuration.

- testcases/InstallUpstreamKernel.py
This Patch checks for the red-hat OS version and uses the appropriate grub cmd, based on the OS version.
> Updating grub cmd based OS version

- testcases/MachineConfig.py
Vtpm version will be set according to Power10/Power11 to 2.0
> Power11 processor mode is added to enable vtpm

- testcases/OpTestKernelTest.py
Currently cpu value is being returned as floating point, which is resulting in make command failure. Changing it to return int value.
Below is the snippet of the logs before and after the change.
Before:
`console-expect]#make -j 9.0 -s
make -j 9.0 -s
make[1]: *** No rule to make target '9.0'.  Stop.
make: *** [Makefile:240: __sub-make] Error 2
[console-expect]#echo $?
echo $?
2`
After this patch:
`[console-expect]#make -j 9 -s
make -j 9 -s
echo "#include <asm-generic/bpf_perf_event.h>" > arch/powerpc/include/generated/uapi/asm/bpf_perf_event.h`
> Fixing Typecast issue

- testcases/OpTestHtxBootme.py
The test is performed in below manner
1. Starts Htx workload on Nic devices with net.mdt
2. Starts bootme which auto reboots the lpar every 30 minutes
3. wait for reboot and check htxerror logs after reboot, Htx must continue without any errors
4. Stop bootme
5. Stop Htx workload
Param : "boot_count" must be given from machine.conf file. The param is for the number of counts the reboot cycle must happen. Default is 6
> Adding HtxBootme test for Nic Devices on OpTest

- CONFIG.YMAL
- common/OpTestHMC.py
- common/OpTestSysinfo.py
This utility is designed to collect information across different test stack like OS, HMC, VIOS sysinfo etc..
sysinfo collected for every run before the test starts.
The flow is as below:
The OpTestSysinfo has different functions for different stack like OS, HMC, VIOS. Whenever the PS1 is initiated, the OpTestSysinfo module collects the data from the respective stack.
> Sysinfo utility to record system information

- common/OpTestInstallUtil.py
sed expression is failing.. So updated the expression which matches and replaces the string, which also avoids the escape issues by using | as the delimiter
> OpTestInstallUtil.py-AssertionError: KernelArgTest failed to update kernel args

- testcases/PowerNVDump.py
The patch takes care of restarting the kdump service after restoring to the original kdump cfg file.
When done, the next kdump iteration will run with the default kdump configuration. This will take care of post crash setup after the NFS, SSH kdump runs.
> restart kdump service after copying cfg file

- common/OpTestHMC.py
- testcases/MachineConfig.py
Ex: Passing vpmem=4 configures 4 vpmem volumes 1 with affinity enabled and 3 with affinity disabled.
> Added support to configure multiple vpmem volumes.

- op-test
- testcases/OpTestKernelDump.py
Now the testcase also has PowerVM LPAR kernel dump support, we need to change the name to more meaningful name to OpTestKernelDump
> Rename PowerNVDump test to correct name

- testcases/OpTestKernelTest.py
Fixing couple of bugs in the Git-Bisect code.
Commit_1: Fixes NameError: name 'linux_path' is not defined
linux_path variable is not referenced properly in the scope of build_kernel(), hence fixing the same.
Commit_2: Typecast issue
CPU type is of floating type, which causes build to fail. Changing the typecast to int().
> Git Bisect Code Fixes

- common/OpTestHost.py
- testcases/OpTestKernelTest.py
Add method to get online cpus instead of cpu cores replace host_get_core_count with host_get_online_cpus
> gitbisect: get online cpu count instead of cpu cores

- testcases/OpTestKernelTest.py
Optimized the code into single class so as to resuse the same code from build to boot. Having a single class will help integrate in the jenkins shell
1. No more build and boot class separate, its single class
2. build and boot functions are made class methods so it can be reused during bisection bad path
3. a common json generated for build and boot, unlike seperate jsons earlier
4. no more build/boot tags.. and goodcommit is one now for both build and boot failure.
> Final Integration code for build/boot bisection

- testcases/OpTestKernelDump.py
Removed explicit vmcore checks as they already been taken care in verify_dump_file() function
> OpTestKernelDump.py: Fixed two fadump junk and off value testcases

- testcases/OpTestKernelTest.py
Without this timeout, command is timing out, even while rm -rf is on progress. This resulting in CI builds failure.
> Adding a timeout parameter for rm -rf command

- testcases/OpTestKernelDump.py
For Sles16 fadump enablement is different so added a condition as per the requirement
> OpTestKernelDump.py: Added fadump enablement for sles16

- testcases/OpTestKernelDump.py
In Rhel systemctl restart kdump service is not regenerating the initramfs correctly. So changed that accordingly
> OpTestKernelDump.py: fixed KernelCmdlineParamTest() failure
